SDA-SE/sda-dropwizard-commons

- sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/OpaRequestsIT.java
- sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/OpaResponsesIT.java
- sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/OpaRuleIT.java
- sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/test/OpaBundeTestAppConfiguration.java
- sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/test/OpaBundleTestApp.java
- sda-commons-server-auth/README.md
- sda-commons-server-auth/src/main/java/org/sdase/commons/server/opa/filter/OpaAuthFilter.java
- sda-commons-server-auth/src/main/java/org/sdase/commons/server/opa/filter/model/OpaInput.java
- sda-commons-server-auth/src/main/java/org/sdase/commons/server/opa/filter/model/OpaRequest.java
This change forwards all incoming HTTP headers to the OPA-Input. They are available as input.headers.<header-name>. We implement this in the scope of KAP-1149 to introduce a way to pass information from the service to the OPA.
> feat(server-auth): forward all http headers to OPA

- build.gradle
- sda-commons-server-kafka-confluent-testing/build.gradle
For now we have to remove the OWASP dependency check as it doesn't work. The current referenced version 4.0.2 doesn't work with our project setup. The latest version 5.3.0 does, however has a version conflict with the current version of the AVRO code generator plugin (velocity templates dependency). This is fixed in the latest version of the AVRO code generator plugin, however this is only compatible to the latest Confluent, Avro and Kafka versions. We still have a Kafka (and related components) upgrade on our roadmap.
However, as we also expect our downstream project to scan for dependency issues using OWASP dependency check, we should still stay alerted about dependency issues. In addition dependabot is configured to provide use with security updates.
> chore: remove OWASP dependency check

- sda-commons-server-auth/src/main/java/org/sdase/commons/server/auth/service/AuthRSA256Service.java
If token verification fails because the token is expired, we are in a situation were we can't do anything about this in operations. Instead of an error, we should log a warning here to reduce noise in production.
> fix: make expired tokens a warning 

- .github/workflows/gradle.yml
The build fails very often and stops us from working efficiently. We should still test Windows builds, to find issues with Windows systems. Java 11 is still tested in general on Linux.
> chore: disable Java 11 on Windows build

- sda-commons-server-mongo-testing/src/main/java/org/sdase/commons/server/mongo/testing/MongoDbRule.java
Since the latest update MacOS asks for every started MongoDB in test for
firewall access confirmation. When keeping the executable name fixed,
this confirmation request only annoys once.
> Keep the MacOS firewall silent when executing tests with MongoDB

- sda-commons-server-opentracing/src/main/java/org/sdase/commons/server/opentracing/OpenTracingBundle.java
- sda-commons-server-opentracing/src/main/java/org/sdase/commons/server/opentracing/servlet/AdminServletSpanDecorator.java
- sda-commons-server-opentracing/src/test/java/org/sdase/commons/server/opentracing/OpenTracingBundleTest.java
While one normally don't want to trace the admin port, this allows to group the spans that are currently emitted by health checks. Later on we can disable tracing for these spans and their child spans.
> feat: add tracing to admin port

- sda-commons-server-jaeger/src/main/java/org/sdase/commons/server/jaeger/JaegerBundle.java
Jaeger automatically shuts down on JVM exit. However, we are running mutliple Drowpizard applications during testing without shutting down the Jaeger tracer. This can cause memory leaks.
> fix(server-jaeger): shutdown jaeger tracer on application exit

- sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/KafkaTopicIT.java
Now uses the default timeout of 10s.
> test(server-kafka): increase timeout of createTopic

- sda-commons-server-dropwizard/README.md
- sda-commons-server-dropwizard/build.gradle
- sda-commons-server-dropwizard/src/main/java/org/sdase/commons/server/dropwizard/bundles/DefaultLoggingConfigurationBundle.java
- sda-commons-server-dropwizard/src/main/java/org/sdase/commons/server/dropwizard/logging/ConsoleAppenderInjectorSourceProvider.java
- sda-commons-server-dropwizard/src/test/java/org/sdase/commons/server/dropwizard/bundles/DefaultLoggingConfigurationBundleWithConsoleAppenderTest.java
- sda-commons-server-dropwizard/src/test/java/org/sdase/commons/server/dropwizard/bundles/DefaultLoggingConfigurationBundleWithEmptyConfigTest.java
- sda-commons-server-dropwizard/src/test/java/org/sdase/commons/server/dropwizard/bundles/DefaultLoggingConfigurationBundleWithJsonLoggingEnabledTest.java
- sda-commons-server-dropwizard/src/test/java/org/sdase/commons/server/dropwizard/bundles/DefaultLoggingConfigurationBundleWithUnconfiguredConsoleAppenderTest.java
- sda-commons-server-dropwizard/src/test/java/org/sdase/commons/server/dropwizard/bundles/DefaultLoggingConfigurationBundleWithoutAppendersKeyTest.java
- sda-commons-server-dropwizard/src/test/java/org/sdase/commons/server/dropwizard/bundles/DefaultLoggingConfigurationBundleWithoutConsoleAppenderTest.java
- sda-commons-server-dropwizard/src/test/java/org/sdase/commons/server/dropwizard/bundles/DefaultLoggingConfigurationBundleWithoutLoggingKeyTest.java
You can activate JSON logging for normal log messages and request log via the ENABLE_JSON_LOGGING environment variable.
> feat: add support for JSON logging

- sda-commons-server-mongo-testing/src/main/java/org/sdase/commons/server/mongo/testing/MongoDbRule.java
- sda-commons-server-morphia/src/main/java/org/sdase/commons/server/morphia/MorphiaBundle.java
- sda-commons-server-morphia/src/main/java/org/sdase/commons/server/morphia/converter/LocalDateConverter.java
- sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleCustomConverterIT.java
- sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleDefinedClassIT.java
- sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleDisableLocalDateConvertersIT.java
- sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleEnsureIndexesIT.java
- sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleHealthCheckIT.java
- sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleLocalDateConvertersIT.java
- sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleNoEntityDefinedIT.java
- sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleScanPackageByMarkerClassIT.java
- sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleTracingIT.java
- sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleValidationDisabledIT.java
- sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleValidationIT.java
- sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/converter/LocalDateConverterTest.java
This PR will break services that use `java.time.LocalDate` in their Morphia entity classes. A configuration option for backward compatibility has been added. We need to add the following announcement to the release notes manually after the release has been created:
> Add custom converter to store LocalDate without time part
> 
> This way there is no timezone hassle when storing dates without time.
>
> This might break existing services that already use `java.time.LocalDate` in any of their Morphia entity classes.
> 
> - Only `java.time.LocalDate` in entity classes is affected.
> - Only Morphia/MongoDB is affected.
> - Everything is safe with PostgreSQL/JDBC, the REST model, the Jackson mappings.
>
> If your service uses `java.time.LocalDate` in any entity class that is managed with the …
> Add custom converter to store LocalDate without time part

- sda-commons-server-auth-testing/README.md
- sda-commons-server-auth-testing/src/main/java/org/sdase/commons/server/opa/testing/OpaRule.java
- sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/AuthAndOpaIT.java
- sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/OpaRuleIT.java
This change adds support for checking whether the JWT was correctly sent to the OPA. In the old implementation one could use `onRequest(method, path)` to configure an expected request. Now there is a builder approach `onRequest().withMethod(method).withPath(path).withJwt(jwt)` that also allows to check for explicit JWT values. This is also possible for verifying requests: `verify(1, onRequest().withMethod(method).withPath(path).withJwt(jwt))`. There was no functional change in the existing methods.
The existing `onRequest(method, path)` approach was also marked as deprecated since the new approach gives much more flexibility. Futhermore, it should be advised to always check if the JWT is if correctly forwarded to the OPA.
> feat(server-auth-testing): add more flexible request matching to the OPA rule

- sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/ApiClientTimeoutTest.java
- sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/GenericClientTimeoutTest.java
The timeouts of the timeouts tests were to narrow, with the broader timeouts the tests should succeed more often on Windows machines.
> test(client-jersey): make timeout tests less flaky

- sda-commons-server-auth-testing/src/main/java/org/sdase/commons/server/opa/testing/OpaRule.java
- sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/RequestExtraBuilderTest.java
I lost some time in figuring out why my OPA mocks did not match until I realized that I you can not use the same value in the request and the OPA. This PR adds methods for all data types the AuthRule is able to return the JWT. So the OPA mock builder can be used in any case easily.
> Introduce builder methods to mock OPA with all JWT outputs available in AuthRule

- sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/OpaRuleIT.java
- sda-commons-server-auth/README.md
- sda-commons-server-auth/build.gradle
- sda-commons-server-auth/src/main/java/org/sdase/commons/server/opa/OpaBundle.java
- sda-commons-server-auth/src/main/java/org/sdase/commons/server/opa/extension/OpaInputExtension.java
- sda-commons-server-auth/src/main/java/org/sdase/commons/server/opa/extension/OpaInputHeadersExtension.java
- sda-commons-server-auth/src/main/java/org/sdase/commons/server/opa/filter/OpaAuthFilter.java
- sda-commons-server-auth/src/main/java/org/sdase/commons/server/opa/filter/model/OpaInput.java
- sda-commons-server-auth/src/main/java/org/sdase/commons/server/opa/filter/model/OpaRequest.java
- sda-commons-server-auth/src/test/java/org/sdase/commons/server/opa/OpaBundleBodyInputExtensionTest.java
- sda-commons-server-auth/src/test/java/org/sdase/commons/server/opa/OpaBundleTest.java
This PR adds the possibility to add extensions for the `OPAInput` and moves the implementation of the headers to an extension that is enabled by default. It also adds an option to disable this default extension.
> feat(server-auth): make the input extensible for different use cases

- .github/workflows/fossa.yml
- .github/workflows/gradle.yml
- .github/workflows/pull-request-snapshots.yml
Sometimes, especially on Windows runners, the process hangs and we just have an idle build runner. We can fail much early and try to restart the process.
> chore: set lower build timeout

- build.gradle
The recent refactoring in #206 was incomplete. While no jars were published for the -example modules, the pom-files were still uploaded.
> chore: do not configure publishing for the example modules

- .github/workflows/gradle.yml
Sonarcloud issues a warning that Java 8 will not be supported anymore soon.
> chore: run sonarcloud in the Java 11 build

- .github/workflows/upload-release-maven-central.yml
A typo that didn't provide the id of the created staging profile to the upload step.
> chore: read the staging profile id from the outputs context

- sda-commons-server-kafka-confluent-testing/README.md
- sda-commons-server-kafka-confluent/README.md
This PR marks our module for Avro support as deprecated. Deprecation is only stated in the documentation / README.md of the module. Does anyone have a better suggestion?
> docs(server-kafka-confluent): Mark modules as deprecated

- sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/AuthAndOpaIT.java
- sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/OpaJwtPrincipalInjectIT.java
- sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/test/AuthAndOpaBundleTestApp.java
- sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/test/OpaJwtPrincipalEndpoint.java
- sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/test/OpaJwtPrincipalInjectApp.java
- sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/test/PrincipalInfo.java
- sda-commons-server-auth/README.md
- sda-commons-server-auth/src/main/java/org/sdase/commons/server/opa/OpaBundle.java
- sda-commons-server-auth/src/main/java/org/sdase/commons/server/opa/OpaJwtPrincipal.java
- sda-commons-server-auth/src/main/java/org/sdase/commons/server/opa/internal/OpaJwtPrincipalFactory.java
- sda-commons-server-auth/src/main/java/org/sdase/commons/server/opa/internal/OpaJwtPrincipalImpl.java
- sda-commons-server-auth/src/test/java/org/sdase/commons/server/opa/internal/OpaJwtPrincipalFactoryTest.java
In many of our services we add a dedicated class or method that extracts and casts the principal from the injected `SecurityContext`.
To avoid the repeated block of code that always has to be tested, we can inject the `OpaJwtPrincipal` directly to read the constraints defined by the OPA.
Unfortunately there seems to be no option to provide constraints in the context as they depend on the project.
> Provide `OpaJwtPrincipal` as injectable bean

- sda-commons-dependencies/build.gradle
Constraints are evaluated before included BOMs which means that we can't override dependencies included by BOMs with a constraint later. The previous comment said that, but didn't worked and caused mixed versions and a downgrade to a very old version that contains CVEs. This can be fixed by including the kotlin-bom, that also makes sure that all depending modules stay on the same version.
However this doesn't work with 1.3.72 for some reason, so we downgrade to 1.3.50 for now.
> fix(deps): fix overriding the kotlin dependecy (and downgrade to 1.3.50)

- sda-commons-dependencies/build.gradle
- sda-commons-server-swagger/src/test/java/org/sdase/commons/server/swagger/test/SwaggerAssertions.java
This fixes getting mixed versions from several Jetty components like jetty-http which caused 'NoSuchFieldError's when running the application.
> fix(deps): Use same Jetty version as Dropwizard 9.4.18.v20190429

- sda-commons-server-jackson/src/main/java/org/sdase/commons/server/jackson/errors/JerseyValidationExceptionMapper.java
- sda-commons-server-jackson/src/test/java/org/sdase/commons/server/jackson/JacksonConfigurationBundleIT.java
- sda-commons-server-jackson/src/test/java/org/sdase/commons/server/jackson/test/JacksonConfigurationTestApp.java
- sda-commons-server-jackson/src/test/java/org/sdase/commons/server/jackson/test/NameSearchFilterResource.java
- sda-commons-server-jackson/src/test/java/org/sdase/commons/server/jackson/test/SearchFilterResource.java
When using inheritance with `@JsonTypeInfo` like in APIs with complex search filters, we are not able to identify the path of an invalid field to respond with appropriate `invalidParams`.
The invalid path is set to _N/A_ instead of the correct path. This happens because the `JerseyValidationExceptionMapper` only knowns about the superclass defined in the param list of the API method and not about the subclasses.
At the moment we have no solution for this but added a test case in this PR that constructs such a situation and fails.
> Fix validation response in case of inheritance

- sda-commons-dependencies/build.gradle
- sda-commons-server-dropwizard/build.gradle
- sda-commons-server-kafka-confluent/src/test/java/org/sdase/commons/server/kafka/confluent/WrapperKafkaDeserializerIT.java
- sda-commons-server-kafka-confluent/src/test/java/org/sdase/commons/server/kafka/confluent/dropwizard/KafkaAvroIT.java
- sda-commons-server-testing/build.gradle
hamcrest (2.x) and hamcrest-core (1.x) have mostly similar classes 
but are not compatible in all details the later version of hamcrest
comes with Awaitility, so we use that in favour of the older one
served with junit. It is assumed that junit does not use it itself
and therefore has no conflicts due to the changes.
As junit by default provides hamcrest, we still ship it. But it is
not used any more here in favour of AssertJ. All usages of hamcrest 
are replaced with AssertJ.
We need to manage the deprecated dependency hamcrest-core to 
overwrite transitive dependencies. Version 2.2 of hamcrest-core
contains deprecation notices only and has no conflicts with the new
artifact.
> fix(deps): upgrade hamcrest

- sda-commons-dependencies/build.gradle
This PR does not include javax.*-Dependencies that are replaced by jakarta.* in Dropwizard. We will update them when confluent/avro is removed.
> Remove management of depencies that are defined by dropwizard-dependencies

- sda-commons-client-jersey-wiremock-testing/build.gradle
- sda-commons-client-jersey/build.gradle
- sda-commons-dependencies/build.gradle
- sda-commons-dependency-check/src/test/java/org/sdase/commons/dependency/check/DuplicateClassesTest.java
- sda-commons-server-auth/build.gradle
- sda-commons-server-dropwizard/build.gradle
- sda-commons-server-hibernate/build.gradle
- sda-commons-server-jaeger/build.gradle
- sda-commons-server-mongo-testing/build.gradle
- sda-commons-server-morphia/build.gradle
- sda-commons-server-prometheus/build.gradle
- sda-commons-server-s3-testing/build.gradle
- sda-commons-server-s3/build.gradle
- sda-commons-server-swagger/build.gradle
- sda-commons-server-testing/build.gradle
- sda-commons-server-weld-testing/build.gradle
- sda-commons-server-weld/build.gradle
There are still some `javax.*` dependencies that are brought in by dropwizard. I guess we want to ignore those for now?
* javax.transaction:javax.transaction-api (by dropwizard-hibernate)
* javax.servlet:javax.servlet-api (by jetty ➡️ by nearly alle dropwizard modules)
> fix(deps): prefer using jakarta.* over javax.* dependencies that are provided by dropwizard-dependencies

- sda-commons-server-hibernate/src/main/java/org/sdase/commons/server/hibernate/HibernateBundle.java
Registering the bundle causes a warning in the log and has no effect.
The bundle is not context aware.
> fix(server-hibernate): do not register the HibernateBundle at Jersey

- sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/auth/testing/AuthRuleIT.java
- sda-commons-server-auth/src/main/java/org/sdase/commons/server/auth/error/JwtAuthException.java
This PR also adds tests that checks if the error messages are actually the ones that are expected to be returned.
> fix(server-auth): don't include the exception class when a token decoding failed

- sda-commons-client-jersey-example/README.md
- sda-commons-client-jersey-example/src/main/java/org/sdase/commons/client/jersey/JerseyClientExampleApplication.java
- sda-commons-client-jersey-example/src/main/java/org/sdase/commons/client/jersey/JerseyClientExampleConfiguration.java
- sda-commons-client-jersey-example/src/test/java/org/sdase/commons/client/jersey/JerseyClientExampleIT.java
- sda-commons-client-jersey-example/src/test/resources/test-config.yaml
- sda-commons-client-jersey/README.md
- sda-commons-client-jersey/src/main/java/org/sdase/commons/client/jersey/ClientFactory.java
- sda-commons-client-jersey/src/main/java/org/sdase/commons/client/jersey/HttpClientConfiguration.java
- sda-commons-client-jersey/src/main/java/org/sdase/commons/client/jersey/builder/AbstractBaseClientBuilder.java
- sda-commons-client-jersey/src/main/java/org/sdase/commons/client/jersey/builder/ExternalClientBuilder.java
- sda-commons-client-jersey/src/main/java/org/sdase/commons/client/jersey/builder/PlatformClientBuilder.java
- sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/ApiClientConfigurationTest.java
- sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/ClientConfiguredProxyTest.java
- sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/ClientProxyTest.java
- sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/test/ClientTestApp.java
- sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/test/ClientTestConfig.java
- sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/auth/testing/CustomKeyLoaderConfigIT.java
- sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/auth/testing/KeyLoaderProxyIT.java
- sda-commons-server-auth/README.md
- sda-commons-server-auth/src/main/java/org/sdase/commons/server/auth/AuthBundle.java
- sda-commons-server-auth/src/main/java/org/sdase/commons/server/auth/config/AuthConfig.java
- sda-commons-server-auth/src/main/java/org/sdase/commons/server/opa/OpaBundle.java
- sda-commons-server-auth/src/main/java/org/sdase/commons/server/opa/config/OpaClientConfiguration.java
- sda-commons-server-auth/src/main/java/org/sdase/commons/server/opa/config/OpaConfig.java
- sda-commons-server-auth/src/test/java/org/sdase/commons/server/opa/OpaBundleClientConfigurationIT.java
- sda-commons-server-testing/src/main/java/org/sdase/commons/server/testing/SystemPropertyRule.java
- sda-commons-server-testing/src/test/java/org/sdase/commons/server/testing/EnvironmentRuleTest.java
- sda-commons-server-testing/src/test/java/org/sdase/commons/server/testing/SystemPropertyRuleTest.java
Adds a property to the `AuthConfig` in order to use all properties of Dropwizard's original [`HttpClientConfiguration`](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-client/src/main/java/io/dropwizard/client/HttpClientConfiguration.java), including Proxy settings.
Dropwizard also provides the option to override configurations via [system properties](https://www.dropwizard.io/en/latest/manual/core.html#configuration). Thus something like
```sh
java -Ddw.auth.keyLoaderClient.proxyConfiguration.host=asdf server my-config.json
```
should work even if the service doesn't specify the options in the original `config.yml`. This might be an alternative to #453 that is more aligned with the features of Dropwizard.
---
In addition I added an experimental commit that makes our …
> feat(server-auth): add configuration options to the jersey client that is used to load keys

- .dependabot/config.yml
This way it's easier to distinguish updates for the current release and the maintenance branch.
See https://dependabot.com/docs/config-file/#default_labels
> chore(deps): add another label to dependabot PRs

- sda-commons-server-jackson/src/main/java/org/sda/commons/server/jackson/hal/HalLinkInvocationStateUtility.java
- sda-commons-server-jackson/src/main/java/org/sda/commons/server/jackson/hal/HalLinkMethodInvocationException.java
- sda-commons-server-jackson/src/main/java/org/sda/commons/server/jackson/hal/HalLinkProvider.java
- sda-commons-server-jackson/src/main/java/org/sda/commons/server/jackson/hal/LinkResult.java
- sda-commons-server-jackson/src/main/java/org/sdase/commons/server/jackson/JacksonConfigurationBundle.java
- sda-commons-server-jackson/src/test/java/org/sda/commons/server/jackson/hal/HalLinkProviderTest.java
We have identified that the HalLinkProvider is often implemented redundantly if the required entity link is to be provided. 
Here is a suggestion how we can build the HALLink in a comfortable way.
> feat: add HalLinkProvider to sda-commons-server-jackson

- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/consumer/MessageListener.java
- sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/consumer/AutocommitStrategyTest.java
The new test `AutocommitStrategyTest.java` mainly consists of the old `MessageListenerTest` of sda-commons 1. I'm not sure why the complete test was deleted because I think many tests still apply to the new `MessageListenerStrategy`.
The code change handles "null" as a result of `KafkaConsumer#partitionsFor` which caused a `NullPointerException`.
> fix(server-kafka): Fix waiting for topic creation

- sda-commons-server-jackson/src/main/java/org/sda/commons/server/jackson/hal/HalLinkInvocationStateUtility.java
- sda-commons-server-jackson/src/test/java/org/sda/commons/server/jackson/hal/HalLinkProviderTest.java
In some cases it could be required that the QueryParam is nullable. Maybe you want to link to a specific set of entities which are prefiltered?
```
URI uri = linkTo(methodOn(MedicalHistoryService.class).getEvents("12345", null, null, null, null, null, null)).asUri();
assertThat(uri).hasPath("/medicalEvents").hasParameter("insuredPersonId", "12345");
assertThat(uri.toString()).isEqualTo("/medicalEvents?insuredPersonId=12345");
```
> fix(server-jackson): support nullable query params in the HalLinkProvider

- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/KafkaConfiguration.java
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/config/HealthCheckConfig.java
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/health/KafkaHealthCheck.java
- sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/health/KafkaHealthCheckIT.java
Adds new configuration to kafka for setting the value in seconds. Default is 2.
Example:
```
kafka:
...
healthCheck:
timeoutInSeconds: 2
```
> feat(server-kafka): Make timeout for KafkaHealthCheck configurable

- sda-commons-server-dropwizard/README.md
We noticed that we can't link it.
> docs: add a heading for JSON logging

- sda-commons-server-kafka/README.md
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/KafkaConfiguration.java
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/KafkaProperties.java
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/config/AdminConfig.java
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/config/Security.java
- sda-commons-server-kafka/src/test/java/com/salesforce/kafka/test/SharedKafkaTestResourceScram.java
- sda-commons-server-kafka/src/test/java/com/salesforce/kafka/test/listeners/SaslScramListener.java
- sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/CleanupJaasConfigurationRule.java
- sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/KafkaBundleWithSaslPlainIT.java
- sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/KafkaBundleWithSaslScramIT.java
- sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/config/KafkaPropertiesSpec.java
- sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/config/KafkaPropertiesTest.java
- sda-commons-server-kafka/src/test/resources/sasl-jaas.conf
- sda-commons-server-kafka/src/test/resources/sasl-scram-jaas.conf
- sda-commons-server-kafka/src/test/resources/test-config-default.yml
This PR adds support for the `SCRAM-SHA-512` SASL-mechanism.
The changes:
1. Automatically select the correct login module for the SASL mechanisms (`PLAIN`-> `PlainLoginModule`, `SCRAM-SHA-*` -> `ScramLoginModule`). Other mechanisms lead to a failing bundle. Those should be used with the `config` overrides or an sda-dropwizard-commons PR.
2. The `AdminConfig` lacked a `config` property to provide custom configurations if needed.
3. Don't require username or password to configure the security protocol. `SSL` doesn't need credentials, but it wasn't obvious that one still need to fill the username and password fields before.
4. A new Readme-section that describes the different auth-configurations.
5. A new test that checks if the bundle can connect to a `SASL_PLAINTEXT` / `PLAIN` Kafka …
> feat(server-kafka): allow the configuration of the sasl.mechanism

- sda-commons-shared-asyncapi/src/main/java/org/sdase/commons/shared/asyncapi/AsyncApiGenerator.java
- sda-commons-shared-asyncapi/src/main/java/org/sdase/commons/shared/asyncapi/JsonSchemaGenerator.java
- sda-commons-shared-asyncapi/src/main/java/org/sdase/commons/shared/asyncapi/internal/JsonNodeUtil.java
- sda-commons-shared-asyncapi/src/test/java/org/sdase/commons/shared/asyncapi/AsyncApiGeneratorTest.java
- sda-commons-shared-asyncapi/src/test/java/org/sdase/commons/shared/asyncapi/JsonSchemaGeneratorTest.java
- sda-commons-shared-asyncapi/src/test/java/org/sdase/commons/shared/asyncapi/internal/JsonNodeUtilTest.java
- sda-commons-shared-asyncapi/src/test/resources/asyncapi_expected.yaml
- sda-commons-shared-asyncapi/src/test/resources/schema_expected.yaml
Sorting the schema makes it easier to find entities in a definition but also allows to compare them easier.
This might break assertions on generated files as the order of the content changes, but beside that there are no changes to
content.
Btw. changing the order in the `_expected` files has no influence on the tests, but I did it for fun 😉
> feat(shared-asyncapi) sort definitions in generated json schema and asyncapi files

- sda-commons-server-kafka/README.md
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/KafkaBundle.java
- sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/dropwizard/KafkaWithoutHealthCheckTestApplication.java
- sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/health/KafkaWithoutHealthCheckIT.java
An alternativ solution could be a field in the kafka configuration yml instead of `withoutHealthCheck()` in the builder.
> feat: allow disabling of kafka health check

- sda-commons-server-errorhandling-example/src/main/java/org/sdase/commons/server/errorhandling/rest/model/RequestObject.java
- sda-commons-server-hibernate-example/src/main/java/org/sdase/commons/server/hibernate/example/rest/model/PersonResource.java
- sda-commons-server-jackson/src/main/java/org/sdase/commons/server/jackson/JacksonConfigurationBundle.java
- sda-commons-server-jackson/src/main/java/org/sdase/commons/server/jackson/errors/JacksonPropertyNodeNameProvider.java
- sda-commons-server-jackson/src/main/java/org/sdase/commons/server/jackson/errors/JerseyValidationExceptionMapper.java
- sda-commons-server-jackson/src/test/java/org/sdase/commons/server/jackson/JacksonConfigurationBundleIT.java
- sda-commons-server-jackson/src/test/java/org/sdase/commons/server/jackson/test/NameNotRepeatedValidator.java
- sda-commons-server-jackson/src/test/java/org/sdase/commons/server/jackson/test/NameSearchFilterResource.java
- sda-commons-server-jackson/src/test/java/org/sdase/commons/server/jackson/test/NestedNestedResource.java
- sda-commons-server-jackson/src/test/java/org/sdase/commons/server/jackson/test/NestedResource.java
- sda-commons-server-jackson/src/test/java/org/sdase/commons/server/jackson/test/ValidationResource.java
- sda-commons-server-morphia/src/main/java/org/sdase/commons/server/morphia/MongoConfiguration.java
- sda-commons-server-s3/src/main/java/org/sdase/commons/server/s3/S3Configuration.java
Previously, we used custom code to correctly resolve the property names (if used with `@JsonProperty("name")`). Hibernate now supports providing a custom property node name provider (see https://github.com/hibernate/hibernate-validator/pull/1029). They also provide an example implementation for Jackson in their documentation. After applying this custom `propertyNodeNameProvider`, we can use an existing function from Dropwizard (`ConstraintMessage.isRequestEntity(...)`) that computes the correct property path.
Closes #611
> fix(server-jackson): use a custom hibernate node name provider to resolve the paths in the validation exceptions

- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/KafkaProperties.java
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/config/ProtocolType.java
- sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/config/KafkaPropertiesTest.java
The service emits a warning in the log if the `sasl.jaas.config` property is set even if the security protocol doesn't support SASL:
> The configuration 'sasl.jaas.config' was supplied but isn't a known config.
This behavior was introduced in #548 that allowed the configuration of `SSL` without configured (and unneeded) user credentials.
> fix(server-kafka): only configure the sasl settings if a sasl protocol is configured

- sda-commons-dependencies/build.gradle
We get dependency conflicts when an application uses both wiremock and json-unit-assertj in the same classpath. We currently don't get a conflict in sda-dropwizard-commons since json-unit-assertj is only included as a test dependency.
I'm not sure if this is a smart decision. Feel free to comment 😄
> fix(deps): align json-unit-core in all dependencies

- sda-commons-client-jersey/README.md
- sda-commons-client-jersey/src/main/java/org/sdase/commons/client/jersey/proxy/ApiClientInvocationHandler.java
- sda-commons-client-jersey/src/main/java/org/sdase/commons/client/jersey/proxy/annotation/SuppressConnectTimeoutErrorsToNull.java
- sda-commons-client-jersey/src/main/java/org/sdase/commons/client/jersey/proxy/annotation/SuppressHttpErrorsToNull.java
- sda-commons-client-jersey/src/main/java/org/sdase/commons/client/jersey/proxy/annotation/SuppressProcessingErrorsToNull.java
- sda-commons-client-jersey/src/main/java/org/sdase/commons/client/jersey/proxy/annotation/SuppressReadTimeoutErrorsToNull.java
- sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/proxy/annotation/SuppressConnectTimeoutErrorsToNullTest.java
- sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/proxy/annotation/SuppressHttpErrorsToNullTest.java
- sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/proxy/annotation/SuppressProcessingErrorsToNullTest.java
- sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/proxy/annotation/SuppressReadTimeoutErrorsToNullTest.java
We realized, that client errors are handled in only two ways very often:
- some errors are mitigated in the same way, weather it is a 404 or a 403
- all other errors are rethrown to produce a 500 for the caller
Therefore we wrote a lot of code to catch, verify and handle exceptions.
This code can be avoided with the new suppression annotations.
Consumers may still handle exceptions for technical reasons, e.g. do a retry on connection errors, but use the suppression feature for business implementation if for example 404 is an expected result.
> Provide annotations to suppress exceptions when using API clients

- sda-commons-starter-example/config.yaml
- sda-commons-starter-example/local-config.yaml
- sda-commons-starter-example/src/main/java/org/sdase/commons/starter/example/SdaPlatformExampleApplication.java
- sda-commons-starter-example/src/test/java/org/sdase/commons/starter/example/SdaPlatformExampleApplicationIT.java
- sda-commons-starter/README.md
- sda-commons-starter/src/main/java/org/sdase/commons/starter/SdaPlatformBundle.java
- sda-commons-starter/src/main/java/org/sdase/commons/starter/SdaPlatformConfiguration.java
- sda-commons-starter/src/main/java/org/sdase/commons/starter/builder/InitialPlatformBundleBuilder.java
- sda-commons-starter/src/test/java/org/sdase/commons/starter/AuthBuilderTest.java
- sda-commons-starter/src/test/java/org/sdase/commons/starter/FilterPriorityTest.java
- sda-commons-starter/src/test/java/org/sdase/commons/starter/SdaPlatformBundleAppTest.java
- sda-commons-starter/src/test/java/org/sdase/commons/starter/SdaPlatformBundleBuilderTest.java
This commit includes two major changes:
(1) - Users can simply add its custom Dropwizard configuration to initialize the application, if the defaults regarding authorization and CORS are used. Please take a look at the example down below.
(2) - The open policy agent is enabled by default, if `.usingSdaPlatformConfiguration()` or `.usingSdaPlatformConfiguration(MyCustomConfiguration.class)` is used to define the application. From now on all users must configure the open policy agent probably, i.e. configure a policy and add OPA properties to the configuration file. Please check out the [auth-bundle](https://github.com/SDA-SE/sda-dropwizard-commons/tree/master/sda-commons-server-auth) for detailed information.
Example:
Instead of writing the following:
```java
public class …
```
> feat(starter): optimize the use of the configuration in the starter bundle

- sda-commons-server-jackson/src/main/java/org/sda/commons/server/jackson/hal/HalLinkMethodInvocationException.java
- sda-commons-server-jackson/src/main/java/org/sda/commons/server/jackson/hal/HalLinkProvider.java
- sda-commons-server-jackson/src/main/java/org/sda/commons/server/jackson/hal/LinkResult.java
- sda-commons-server-jackson/src/main/java/org/sdase/commons/server/jackson/JacksonConfigurationBundle.java
- sda-commons-server-jackson/src/main/java/org/sdase/commons/server/jackson/hal/HalLinkInvocationStateUtility.java
- sda-commons-server-jackson/src/main/java/org/sdase/commons/server/jackson/hal/HalLinkMethodInvocationException.java
- sda-commons-server-jackson/src/main/java/org/sdase/commons/server/jackson/hal/HalLinkProvider.java
- sda-commons-server-jackson/src/main/java/org/sdase/commons/server/jackson/hal/LinkResult.java
- sda-commons-server-jackson/src/test/java/org/sdase/commons/server/jackson/hal/HalLinkProviderTest.java
All classes have been moved to `org.sdase.`
The change should be backward compatible therefore the tests still point to the deprecated classes.
Once the deprecated code is removed, the new exception must be thrown and the test must use the types from the same package.
> fix: deprecate accidentally introduced package `org.sda.`

- sda-commons-server-openapi-example/src/main/java/org/sdase/commons/server/openapi/example/OpenApiExampleApplication.java
- sda-commons-server-prometheus-example/src/main/java/org/sdase/commons/server/prometheus/example/MetricExampleApp.java
- sda-commons-starter-example/src/main/java/org/sdase/commons/starter/example/SdaPlatformExampleApplication.java
- sda-commons-starter-example/src/test/java/org/sdase/commons/starter/example/SdaPlatformExampleApplicationIT.java
- sda-commons-starter/README.md
- sda-commons-starter/build.gradle
- sda-commons-starter/src/main/java/org/sdase/commons/starter/SdaPlatformBundle.java
- sda-commons-starter/src/main/java/org/sdase/commons/starter/SdaPlatformConfiguration.java
- sda-commons-starter/src/main/java/org/sdase/commons/starter/builder/CustomConfigurationProviders.java
- sda-commons-starter/src/main/java/org/sdase/commons/starter/builder/InitialPlatformBundleBuilder.java
- sda-commons-starter/src/test/java/org/sdase/commons/starter/AuthBuilderTest.java
- sda-commons-starter/src/test/java/org/sdase/commons/starter/ConsumerTokenBuilderTest.java
- sda-commons-starter/src/test/java/org/sdase/commons/starter/CorsBuilderTest.java
- sda-commons-starter/src/test/java/org/sdase/commons/starter/FilterPriorityTest.java
- sda-commons-starter/src/test/java/org/sdase/commons/starter/JacksonBuilderTest.java
- sda-commons-starter/src/test/java/org/sdase/commons/starter/OpenAPIBuilderTest.java
- sda-commons-starter/src/test/java/org/sdase/commons/starter/SdaPlatformBundleBuilderTest.java
- sda-commons-starter/src/test/java/org/sdase/commons/starter/SecurityBuilderTest.java
- sda-commons-starter/src/test/java/org/sdase/commons/starter/test/StarterApp.java
With this change, the consumer token for incoming HTTP request is optional by default. Consumer-Token is only used for logging and metrics. It is more or less used for a tracing in a simple way. Technically the consumer token support is removed from the `SdaPlatformBundle` and `SdaPlatformConfiguration`. The `sda-commons-server-consumer` is left as is, because it is used in the `sda-commons-server-starter`.
> feat(starter): use optional consumer token by default

- sda-commons-server-testing/README.md
Such a table with fixed versions is prone to get out of date, we should remove it. Users can view the BOM instead.
> docs(server-testing): remove version table

- sda-commons-server-swagger/README.md
- sda-commons-server-testing/README.md
- sda-commons-server-testing/src/main/java/org/sdase/commons/server/testing/GoldenFileAssertions.java
- sda-commons-server-testing/src/test/java/org/sdase/commons/server/testing/GoldenFileAssertionsTest.java
Take two on #666.
This refactors
```java
GoldenFileAssertions.assertThat(filePath).hasContentAndUpdateGolden(expected);
GoldenFileAssertions.assertThatYaml(filePath).hasContentAndUpdateGolden(expected);
```
to
```java
GoldenFileAssertions.assertThat(filePath).hasContentAndUpdateGolden(expected);
GoldenFileAssertions.assertThat(filePath).hasYamlContentAndUpdateGolden(expected);
```
to better match the AssertJ style.
This also adds a clarification that one should prefer the first option since it has better outputs. The AsyncAPI and OpenAPI generations are automatically sorted and stable. The swagger export is problematic and not easy to fix.
PS: I cancelled the old release to not need a breaking change.
> fix(server-testing): refactor the golden-file-assertions api to match the assertThat() pattern

- catalog-info.yaml
Might not be intermediately visible in Backstage.
> chore: fix platform-team group name in catalog-info

- sda-commons-server-prometheus/README.md
- sda-commons-server-prometheus/src/main/java/org/sdase/commons/server/prometheus/PrometheusBundle.java
- sda-commons-server-prometheus/src/main/java/org/sdase/commons/server/prometheus/health/HealthCheckAsPrometheusMetricServlet.java
- sda-commons-server-prometheus/src/main/java/org/sdase/commons/server/prometheus/health/HealthCheckMetricsCollector.java
- sda-commons-server-prometheus/src/test/java/org/sdase/commons/server/prometheus/PrometheusBundleTest.java
- sda-commons-server-prometheus/src/test/java/org/sdase/commons/server/prometheus/health/HealthCheckMetricsCollectorTest.java
Previously these metrics were only available at the additional /healthcheck/prometheus endpoint that is now deprecated.
> feat: include metrics for health checks at /metrics/prometheus

- sda-commons-dependencies/build.gradle
- sda-commons-server-hibernate-testing/build.gradle
Although it doesn't hurt us, https://github.com/database-rider/database-rider/issues/104 blocked us for a long time for upgrading, but is fixed now.
> Upgrade db rider

- .github/workflows/mongodb.yml
- sda-commons-server-mongo-testing/README.md
- sda-commons-server-mongo-testing/src/main/java/org/sdase/commons/server/mongo/testing/MongoDbRule.java
- sda-commons-server-mongo-testing/src/main/java/org/sdase/commons/server/mongo/testing/StartLocalMongoDbRule.java
- sda-commons-server-mongo-testing/src/main/java/org/sdase/commons/server/mongo/testing/UseExistingMongoDbRule.java
- sda-commons-server-mongo-testing/src/main/java/org/sdase/commons/server/mongo/testing/internal/DownloadConfigFactoryUtil.java
- sda-commons-server-mongo-testing/src/test/java/org/sdase/commons/server/mongo/testing/MongoDbRuleTest.java
- sda-commons-server-mongo-testing/src/test/java/org/sdase/commons/server/mongo/testing/StartLocalMongoDbRuleTest.java
- sda-commons-server-mongo-testing/src/test/java/org/sdase/commons/server/mongo/testing/UseExistingMongoDbRuleTest.java
- sda-commons-server-mongo-testing/src/test/java/org/sdase/commons/server/mongo/testing/internal/DownloadConfigFactoryUtilTest.java
- sda-commons-server-morphia-example/src/test/java/org/sdase/commons/server/morphia/example/MorphiaApplicationIT.java
- sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleCustomConverterIT.java
- sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleDefinedClassIT.java
- sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleEnsureIndexesIT.java
- sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleHealthCheckIT.java
- sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleLocalDateConvertersIT.java
- sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleNoEntityDefinedIT.java
- sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleScanPackageByMarkerClassIT.java
- sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleTracingIT.java
- sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleValidationDisabledIT.java
- sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleValidationIT.java
This PR introduces an optional environment variable with a MongoDB Connection String.
If `TEST_MONGODB_CONNECTION_STRING` is set in the test environment, the MongoDbRule will not start a local database but provides config for applications in test to use the database in the environment.
This PR prepares for testing against production ready databases (like AWS DocumentDB) that can't be bootstrapped with Flapdoodle or other tools. As before no local database is needed. If no such DB is configured for the environment, Flapdoodle will download and start a local MongoDB instance.
This feature may also be used locally with a running MongoDB to run the tests faster.
Preparing the tests to support external MongoDBs has some requirements that are named in the README of the module.
As this feature …
> MongoDB Testing: Provide option to create test environments with a real MongoDB

- build.gradle
- sda-commons-client-jersey-wiremock-testing/README.md
- sda-commons-client-jersey-wiremock-testing/build.gradle
- sda-commons-client-jersey-wiremock-testing/src/main/java/org/sdase/commons/client/jersey/wiremock/testing/WireMockClassExtension.java
- sda-commons-client-jersey-wiremock-testing/src/main/java/org/sdase/commons/client/jersey/wiremock/testing/WireMockExtension.java
- sda-commons-client-jersey-wiremock-testing/src/test/java/org/sdase/commons/client/jersey/wiremock/testing/WireMockClassExtensionTest.java
- sda-commons-client-jersey-wiremock-testing/src/test/java/org/sdase/commons/client/jersey/wiremock/testing/WireMockExtensionTest.java
- sda-commons-server-testing/README.md
- sda-commons-server-testing/build.gradle
- sda-commons-shared-error/build.gradle
*1 This PR enables JUnit 5 for sda-commons*
- it adds dependencies to junit-jupiter-api
- it adds the jupiter and vintage engines as test runtime dependencies
- configures the main test plugin to use junit 5
These changes replace PR #740
*2 It adds extensions for spinning up Wiremock*
Since there is no official support (yet?) from Wiremock we decided to simply create our own extensions to replace the old JUnit 4 rules.
See: https://github.com/tomakehurst/wiremock/issues/684
> feat(wiremock-testing): add jupiter support for wiremockRule and wiremockClassRule

- sda-commons-dependencies/build.gradle
- sda-commons-server-kafka-testing/README.md
- sda-commons-server-kafka-testing/build.gradle
- sda-commons-server-kafka-testing/src/main/java/org/sdase/commons/server/kafka/confluent/testing/KafkaBrokerEnvironmentRule.java
- sda-commons-server-kafka-testing/src/test/java/org/sdase/commons/server/kafka/confluent/testing/KafkaJUnit5IT.java
- sda-commons-server-kafka-testing/src/test/resources/test-config.yaml
This PR mainly adds a new dependency to com.salesforce.kafka.test:kafka-junit5 which provides a JUnit 5 extension to start a Kafka broker
Moreover it adjusts the documentation and marks the KafkaBrokerEnvironmentRule as deprecated.
The code was taken over from PR #716
> Add JUnit 5 support for Kafka testing

- .github/workflows/upload-release-maven-central.yml
The notification is send to the maintainer slack channel.
> chore: add a notification if maven central upload fails

- sda-commons-server-mongo-testing/src/main/java/org/sdase/commons/server/mongo/testing/StartLocalMongoDb.java
- sda-commons-server-mongo-testing/src/test/java/org/sdase/commons/server/mongo/testing/MongoDbVersionTest.java
- sda-commons-server-mongo-testing/src/test/java/org/sdase/commons/server/mongo/testing/StartLocalMongoDbLazyHolderTest.java
- sda-commons-server-mongo-testing/src/test/java/org/sdase/commons/server/mongo/testing/StartLocalMongoDbRuleTest.java
- extract mongodb executable to fixed path and filename to avoid recurring firewall requests on mac
- move some tests to separate class to avoid clashes with conflicting mongodb executables
Since its not a change to the behaviour of the code, only runs on MacOS and can not be really covered by tests, can we accept the low code coverage here?
> fix: provide fixed path and name to mongod executable

- sda-commons-server-mongo-testing/src/main/java/org/sdase/commons/server/mongo/testing/StartLocalMongoDb.java
Downloaded files will be extracted to the temp directory; executable gets unique name
Fixes https://github.com/SDA-SE/sda-dropwizard-commons/issues/838
> fix(server-mongo-testing): Improve concurrent builds with Flapdoodle

- sda-commons-server-jackson/src/main/java/org/sdase/commons/server/jackson/hal/HalLinkInvocationStateUtility.java
- sda-commons-server-jackson/src/main/java/org/sdase/commons/server/jackson/hal/HalLinkProvider.java
- sda-commons-server-jackson/src/test/java/org/sdase/commons/server/jackson/hal/HalLinkProviderTest.java
HalLinkProvider can create URIs for methods with params that are not annotated as `@QueryParam` or `@PathParam` now. These method parameters are ignored when building the URI.
> fix(server-jackson): fix link creation of HalLinkProvider

- sda-commons-server-morphia/README.md
set default for the mongo caCertificate environment variable in the Readme
so the var is not required in the deployment when adding it to the project.
> docs(server-morphia): set default for mongo caCertificate in Readme

- .github/workflows/fossa.yml
In some (all?) PRs we noticed that the Fossa build does not execute. It fails with missing privileges for installation of the Fossa CLI:
> Run curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
…
> fossas/fossa-cli info checking GitHub for latest tag
> fossas/fossa-cli info found version: 1.1.10 for v1.1.10/linux/amd64
> install: cannot change permissions of ‘/usr/local/bin’: Operation not permitted
> Error: Process completed with exit code 1.
`sudo` will provide enough privileges.
> chore(build): fix fossa workflow

- sda-commons-server-auth/src/test/java/org/sdase/commons/server/auth/service/AuthRSA256ServiceTest.java
- sda-commons-shared-certificates/src/test/java/org/sdase/commons/shared/certificates/ca/ssl/CompositeX509TrustManagerTest.java
Context:
Building sda-dropwizard-commons with Java 17 does not work because it is stricter when internal classes are used. This PR removes 2 imports from package "sun.*".
> test: Remove imports of packages "sun.*"

- sda-commons-server-kafka/src/test/java/com/salesforce/kafka/test/SharedKafkaTestResourceScram.java
Makes it compatible with Java 17
To be honest: I'm a little surprised that it does not seem to be necessary to remove the final modifier. But as long as the tests pass we're good, right? 🤣
> test(server-kafka): No need to access field modifiers

- gradle/wrapper/gradle-wrapper.properties
Gradle 7.2 is necessary to build with Java 17. Although Gradle support for Java 17 [is not yet official](https://github.com/gradle/gradle/issues/16857) - it's planned for Gradle 7.3.
> chore: Update to Gradle 7.2

- .github/workflows/pull-request-snapshots.yml
As dependabot PR builds have no secrets, the pull request artifacts can't be pushed to Nexus.
Disabling this job for dependabot will be one less red build we have to care about or that may confuse us when approving PRs.
> chore: disable snapshots for dependabot PRs

- .github/workflows/java-ci.yml
Failing tests will still fail the build, but there is no easy to read information in the PR.
> chore: disable test result publishing for dependabot PRs

- sda-commons-server-starter/README.md
- sda-commons-server-starter/src/main/java/org/sdase/commons/server/starter/SdaPlatformBundle.java
- sda-commons-server-swagger/README.md
- sda-commons-server-swagger/src/main/java/org/sdase/commons/server/swagger/SwaggerBundle.java
- sda-commons-starter/README.md
Please use sda-commons-starter + sda-commons-server-openapi instead.
> docs: Deprecation for server-starter + server-swagger

- .github/workflows/fossa.yml
- .github/workflows/java-ci.yml
- .github/workflows/mongodb.yml
- .github/workflows/publish-release-maven-central.yml
- .github/workflows/publish-release-sda.yml
- .github/workflows/pull-request-snapshots.yml
- .github/workflows/sonar.yml
Adopt OpenJDK is discontinued and will not get further updates.
> chore: Build with Eclipse Temurin instead of Adopt OpenJDK

- sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/OpaIT.java
- sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/OpaResponsesIT.java
- sda-commons-server-auth/src/main/java/org/sdase/commons/server/opa/OpaBundle.java
- sda-commons-server-hibernate/src/main/java/org/sdase/commons/server/hibernate/NonScanningHibernateBundle.java
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/KafkaProperties.java
- sda-commons-server-opentracing-example/src/main/java/org/sdase/commons/server/opentracing/example/OpenTracingApplication.java
- sda-commons-server-opentracing/src/test/java/org/sdase/commons/server/opentracing/tags/TagUtilsTest.java
- sda-commons-server-swagger/src/main/java/org/sdase/commons/server/swagger/SwaggerBundle.java
- sda-commons-server-weld-testing/src/test/java/org/sdase/commons/server/weld/testing/test/util/BarSupplier.java
Only one reference left where I could not find an easy replacement:
https://github.com/SDA-SE/sda-dropwizard-commons/blob/5bc5822ddcfd7bac22c953be3dba08adfe0c3783/sda-commons-server-jackson/src/main/java/org/sdase/commons/server/jackson/errors/JerseyValidationExceptionMapper.java#L5
> chore: Remove most of the references to Google's Guava library 

- build.gradle
- sda-commons-server-openapi/src/test/java/org/sdase/commons/server/openapi/OpenApiBundleFileIT.java
- sda-commons-server-openapi/src/test/java/org/sdase/commons/server/openapi/apps/test/NaturalPersonResource.java
- sda-commons-server-testing/src/main/java/org/sdase/commons/server/testing/GoldenFileAssertions.java
- sda-commons-server-testing/src/test/java/org/sdase/commons/server/testing/GoldenFileAssertionsTest.java
There seems to be an issue with OpenAPI-Tests when run on windows regarding UTF-8 characters.
- This PR reproduces UTF-8 issues [in the Windows Build](https://github.com/SDA-SE/sda-dropwizard-commons/runs/4864579329?check_suite_focus=true#step:4:9500) 
- and introduces a fix by [defining the source encoding](https://github.com/SDA-SE/sda-dropwizard-commons/pull/1401/commits/34fd56c295ecec88e65390ecafc1ce8146319950).
To solve the issue, the encoding must be set in the `build.gradle` of each affected service. I think there is no way to provide the encoding setting for source code with sda-commons.
> Verify that UTF-8 characters are returned for openapi.yaml

- sda-commons-server-openapi/src/main/java/org/sdase/commons/optional/server/openapi/parameter/embed/EmbedParameterModifier.java
- sda-commons-server-openapi/src/test/java/org/sdase/commons/server/openapi/OpenApiBundleIT.java
- sda-commons-server-openapi/src/test/java/org/sdase/commons/server/openapi/apps/test/OpenApiBundleTestApp.java
- sda-commons-server-openapi/src/test/java/org/sdase/commons/server/openapi/apps/test/PartnerSearchResultResource.java
The error occurred under certain conditions when using the `Schema` annotation for a list of `String`. E.g.
```
@Schema(description = "The list of all partners based on the query request.", required = true)
private List<String> partners;
```
> fix(server-openapi): Fix NPE in the log for lists of String

- .github/workflows/mongodb.yml
- sda-commons-server-mongo-testing/README.md
- sda-commons-server-mongo-testing/src/main/java/org/sdase/commons/server/mongo/testing/MongoDb.java
- sda-commons-server-mongo-testing/src/test/java/org/sdase/commons/server/mongo/testing/MongoDbVersionTest.java
- sda-commons-server-mongo-testing/src/test/java/org/sdase/commons/server/mongo/testing/StartLocalMongoDbClassExtensionTest.java
All MongoDB tests use a MongoDB 4.4.x by default now.
In case of issues, the version can be downgraded in the test by configuration temporarily:
`MongoDbClassExtension.builder().withVersion(specificMongoDbVersion).build()`.
In the midterm, the code should be fixed to be compatible with MongoDB 4.4.
> feat(deps): bump MongoDB version to 4.4.x for all environments

- sda-commons-dependencies/build.gradle
- sda-commons-server-jackson/src/main/java/org/sdase/commons/server/jackson/ObjectMapperConfigurationUtil.java
Overriding Dropwizard's version 2.10.x
Upgrade is related to https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36518
According to comments of issue at Jackson Databind the upgrade does **not** fix the CVE.
https://github.com/FasterXML/jackson-databind/issues/2816
> fix(deps): Upgrade Jackson to 2.13.2

- build.gradle
- failOnVersionConflict.gradle
- sda-commons-dependencies/build.gradle
- sda-commons-dependency-check/build.gradle
Choosing a completely different approach to finding version conflicts.
What's wrong with the built in `failOnVersionConflict`?
* it does not seem to detect conflicts between different configurations/scopes
* it detects conflicts that are handled later by using `enforcedPlatform`
My feeling is that `enforcedPlatform` and `failOnVersionConflict` do not really play well together. I tried to get some help in [Gradle's forum](https://discuss.gradle.org/t/enforcedplatform-not-working-struggling-with-failonversionconflict/42516/2) but got no answers.
The version of `failOnVersionConflict` that I wrote here will:
* collect all effective versions from all (relevant) configurations/scopes, i.e. the version that was determined after constraints of `enforcedPlatform` were applied
* fail if different …
> fix(deps): bump jackson-databind to 2.13.2.2

- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/KafkaBundle.java
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/health/KafkaHealthCheck.java
Fixes #1449
Tested here:
* https://github.com/SDA-SE/partner-consent-stack/pull/296
* https://github.com/SDA-SE/gitops-sdadev-consent/pull/104
* https://argo.sdadev.sda-se.io/applications/consent-stack-pr-104?resource=
> fix(server-kafka): Health check reuses AdminClient

- sda-commons-server-dropwizard/README.md
- sda-commons-server-dropwizard/build.gradle
- sda-commons-server-dropwizard/src/main/java/org/sdase/commons/server/dropwizard/logging/ConsoleAppenderInjectorSourceProvider.java
- sda-commons-server-dropwizard/src/test/java/org/sdase/commons/server/dropwizard/bundles/DefaultLoggingConfigurationBundleWithRequestLogFilterTest.java
- sda-commons-server-dropwizard/src/test/java/org/sdase/commons/server/dropwizard/bundles/DefaultLoggingConfigurationBundleWithoutRequestLogFilterTest.java
- sda-commons-server-dropwizard/src/test/java/org/sdase/commons/server/dropwizard/bundles/test/RequestLoggingTestApp.java
When `DISABLE_HEALTHCHECK_LOGS` is set, request logging of the following paths is suppressed:
- `/ping`
- `/healthcheck`  _(new)_
- `/healthcheck/internal`
- `/metrics` _(new)_
- `/metrics/prometheus`  _(new)_
> feat(server-dropwizard): disable more monitoring paths with `DISABLE_HEALTHCHECK_LOGS`

- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/KafkaBundle.java
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/producer/KafkaMessageProducer.java
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/producer/MessageProducer.java
- sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/producer/KafkaMessageProducerTest.java
This PR exposes the producer.flush() method for clients to use.
BREAKING CHANGE:  MessageProducer Interface is extended.
> feat(server-kafka): add flush to message producer interface and implementation

- sda-commons-server-kafka/build.gradle
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/config/ListenerConfig.java
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/consumer/MessageListener.java
- sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/consumer/MessageListenerErrorIntervalTest.java
When error occurs while consuming a Kafka message, the poll interval is exponentially increased to avoid frequent retries of failed message handling, e.g. due to missing downstream services or unavailable other resources.
This change mitigates some flooding logs and excessive resource consumption occurred in a production environment.
@SDA-SE/sda-commons-maintainer We could set the introduced `pollIntervalFactorOnError` to 1 to be 100% backward compatible with the old implementation. But in my opinion it improves 99% of the services when we don't poll excessively on error. So I would like to increase the poll interval on error by default for all services. What are reasonable values?
> feat(server-kafka): increment poll intervall on errors

- sda-commons-dependencies/build.gradle
* fixes [CVE-2022-34917](https://nvd.nist.gov/vuln/detail/CVE-2022-34917)
* [Release Notes](https://archive.apache.org/dist/kafka/2.8.2/RELEASE_NOTES.html)
> fix(deps): Bump Kafka version to 2.8.2 solving CVE-2022-34917

- sda-commons-server-dropwizard/src/test/java/org/sdase/commons/server/dropwizard/bundles/SystemPropertyAndEnvironmentLookupTest.java
Preparation for Java 17 / version 3. 🦓 
Let's get the PR green: https://github.com/SDA-SE/sda-dropwizard-commons/pull/1643
> test(server-dropwizard): Disable tests that set env vars for Java16+

- sda-commons-dependencies/build.gradle
- sda-commons-server-kafka-testing/build.gradle
Bumps `kafkaVersion` from 2.8.2 to 3.2.3.
Updates `kafka_2.13` from 2.8.2 to 3.2.3
Updates `kafka-clients` from 2.8.2 to 3.2.3
---
updated-dependencies:
- dependency-name: org.apache.kafka:kafka_2.13 dependency-type: direct:production update-type: version-update:semver-major
- dependency-name: org.apache.kafka:kafka-clients dependency-type: direct:production update-type: version-update:semver-major ...
Signed-off-by: dependabot[bot] <support@github.com>
> fix(deps): bump kafkaVersion from 2.8.2 to 3.2.3

- .github/workflows/publish-release-maven-central.yml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> chore: Replace `::set-output` according to documentation

- sda-commons-server-kafka-example/src/main/java/org/sdase/commons/server/kafka/KafkaExampleProducerApplication.java
- sda-commons-server-kafka/README.md
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/KafkaBundle.java
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/builder/ProducerRegistration.java
- sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/AppDisabledKafkaServerIT.java
- sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/AppWithoutKafkaServerIT.java
- sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/KafkaBundleWithConfigIT.java
- sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/KafkaTopicIT.java
Marking as deprecated, because we don't want that the topics be created programmatically. Instead, the developers should created it or aks for the DeVops team to do so. The purpose of this approach is to avoid topic misconfiguration and so the company has more control about created resources
> feat(sda-commons-server-kafka): marking createTopicIfMissing method as deprecated

- sda-commons-server-auth-testing/src/main/java/org/sdase/commons/server/auth/testing/AuthRule.java
BREAKING CHANGE:
Consumers of `AuthRule.applyConfig` should configure their app in test using the `io.dropwizard.testing.junit.DropwizardAppRule`. This breaking change may become obsolete when support for JUnit 4 will be canceled in sda-dropwizard-commons v3.x.x.
> PLP-487: remove deprecated method `applyConfig` of `AuthRule`

- sda-commons-dependencies/build.gradle
FYI: `resilience4j-bom` is not available anymore in version `1.7.1`
> fix(deps): bump resilience4j from 1.7.0 to 1.7.1

- sda-commons-server-jaeger/README.md
- sda-commons-server-jaeger/src/main/java/org/sdase/commons/server/jaeger/JaegerBundle.java
- sda-commons-server-opentracing/README.md
- sda-commons-server-opentracing/src/main/java/org/sdase/commons/server/opentracing/OpenTracingBundle.java
Consider using sda-commons-starter's `SdaPlatformBundle` as base instead of manually adding these bundles.
> fix: Mark Jaeger and OpenTracing bundles as deprecated

- sda-commons-server-morphia/src/main/java/org/sdase/commons/server/morphia/IndexEnsurer.java
Skipping system collections like `system.profile`
> fix(server-morphia): Only re-create indexes of mapped entity classes

- .github/workflows/java-ci.yml
Not sure what went wrong. `with.files` has already been changed to `with.junit_files`. Compare release notes: https://github.com/EnricoMi/publish-unit-test-result-action/releases
> chore: Bump publish-unit-test-result-action to 2.3.0

- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/KafkaProperties.java
- sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/config/KafkaPropertiesCleanupTest.java
The Kafka client will reject such configuration but services may prepare optional config in the config.yml.
A new test has been created to avoid rebase issues with upcoming v3 branch.
There is also an option to specify config for specific consumers and producers. They are fetched from the KafkaBundle directly. As it is not very likely, that optional settings without defaults are used in that cases and it will cause major merge conflicts with v3 when changing the KafkaBundle, this PR does not clean up consumer and producer specific settings.
> fix(server-kafka): remove blank settings from Kafka config properties

- sda-commons-server-cors/build.gradle
- sda-commons-server-kafka/build.gradle
Adding javax.xml.bind:jaxb-api dependency, to fix the warning in the tests: https://github.com/SDA-SE/sda-dropwizard-commons/pull/1469/checks?check_run_id=11056045868
> deps(server-cors): adding java xml bind dependency

- .github/workflows/publish-release-maven-central.yml
- .github/workflows/publish-release-sda.yml
- .github/workflows/pull-request-snapshots.yml
Background: Some JavaDoc Jars have been recreated without resigning in the Maven Central Step.
> chore: align publishing actions

- .github/workflows/fossa.yml
Preparation for v3 - needed to update Spotless (https://github.com/SDA-SE/sda-dropwizard-commons/pull/2079)
> chore: Use Java 11 for Fossa

- sda-commons-server-kafka/build.gradle
- sda-commons-server-opentelemetry/src/test/java/org/sdase/commons/server/opentelemetry/servlet/TracingAsyncListenerIT.java
- Not running tests in parallel on Kafka module, to avoid Kafka server configuration concurrency
- Retrying async open telemetry test, to not fail on windows containers
> fix(tests): fixing test execution

- sda-commons-server-kafka/README.md
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/KafkaBundle.java
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/builder/MessageListenerRegistration.java
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/builder/ProducerRegistration.java
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/config/TopicConfig.java
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/exception/MismatchedTopicException.java
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/topicana/AbstractSpecifiedCount.java
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/topicana/ComparisonResult.java
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/topicana/EvaluationException.java
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/topicana/ExpectedTopicConfiguration.java
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/topicana/MismatchedTopicConfigException.java
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/topicana/PartitionCount.java
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/topicana/ReplicationFactor.java
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/topicana/TopicComparer.java
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/topicana/TopicConfigurationBuilder.java
This feature will be removed in v3, see #2100
> fix(server-kafka): Deprecate classes for topic comparison

- sda-commons-server-s3-testing/src/main/java/org/sdase/commons/server/s3/testing/S3Mock.java
- sda-commons-server-s3-testing/src/test/java/org/sdase/commons/server/s3/testing/S3ClassExtensionTest.java
- sda-commons-server-s3-testing/src/test/java/org/sdase/commons/server/s3/testing/S3MockRuleTest.java
Since S3Mock accepts any authentication provider without validating it, this PR is setting up Anonymous authentication mechanism to avoid unnecessary stack traces like:
`com.amazonaws.SdkClientException: Failed to connect to service endpoint`
> fix(server-s3-testing): fix `SdkClientException` in `S3MockExtension` during test execution

- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/KafkaBundle.java
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/consumer/KafkaHelper.java
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/producer/KafkaMessageProducer.java
- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/producer/MetadataContextAwareKafkaProducer.java
- sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/KafkaBundleMetadataContextProducerIntegrationTest.java
- sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/KafkaBundleWithConfigIT.java
- sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/producer/MetadataContextAwareKafkaProducerTest.java
BREAKING CHANGE: All `KafkaBundle.createProducer` methods return a `Producer` instead of its implementation `KafkaProducer` now. The public API of the `KafkaProducer` is exactly the same as in the interface.
> feat(server-kafka): keep metadata context when producing Kafka messages

- sda-commons-server-jackson/src/main/java/org/sdase/commons/server/jackson/ObjectMapperConfigurationUtil.java
- sda-commons-server-jackson/src/test/java/org/sdase/commons/server/jackson/ProduceInvalidJsonOnFailureTest.java
These errors are the only way to identify a serialisation error on consumer side when e.g. a Json is written directly to the response output stream. Streaming data directly from a source (e.g. a MongoCursor) into the response as chunked encoding is valuable to minimize memory resources but may lead to not identifiable errors (e.g. while mapping from entity model to API model) when the ObjectMapper creates a valid Json after the error when the generator is closed.
> fix(server-jackson): write invalid Json when errors happen while serialization

- sda-commons-dependencies/build.gradle
Bumps `dropwizardVersion` from 2.1.5 to 2.1.6.
Updates `io.dropwizard:dropwizard-bom` & `io.dropwizard:dropwizard-dependencies` from 2.1.5 to 2.1.6
- [Release notes](https://github.com/dropwizard/dropwizard/releases)
- [Commits](https://github.com/dropwizard/dropwizard/compare/v2.1.5...v2.1.6)
> fix(deps): bump dropwizardVersion from 2.1.5 to 2.1.6

- sda-commons-server-dropwizard/src/main/java/org/sdase/commons/server/dropwizard/logging/ConsoleAppenderInjectorSourceProvider.java
- sda-commons-server-dropwizard/src/test/java/org/sdase/commons/server/dropwizard/bundles/DefaultLoggingConfigurationBundleWithEmptyConfigTest.java
- sda-commons-server-dropwizard/src/test/java/org/sdase/commons/server/dropwizard/bundles/DefaultLoggingConfigurationBundleWithJsonLoggingEnabledTest.java
- sda-commons-server-dropwizard/src/test/java/org/sdase/commons/server/dropwizard/bundles/DefaultLoggingConfigurationBundleWithUnconfiguredConsoleAppenderTest.java
- sda-commons-server-dropwizard/src/test/java/org/sdase/commons/server/dropwizard/bundles/DefaultLoggingConfigurationBundleWithoutAppendersKeyTest.java
- sda-commons-server-dropwizard/src/test/java/org/sdase/commons/server/dropwizard/bundles/DefaultLoggingConfigurationBundleWithoutConsoleAppenderTest.java
- sda-commons-server-dropwizard/src/test/java/org/sdase/commons/server/dropwizard/bundles/DefaultLoggingConfigurationBundleWithoutLoggingKeyTest.java
- sda-commons-server-dropwizard/src/test/java/org/sdase/commons/server/dropwizard/bundles/LogLevelSystemPropertyTest.java
Actual log output level is depended on "logging.level" and "logging.appenders.threshold". This fix will set appender threshold to "TRACE". This will allow full control of log output using logging.level. All logging default values can be overwritten.
> fix(server-dropwizard): log level not limited by appender threshold

- sda-commons-dependencies/build.gradle
Release Notes:
* https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.17.0
* https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.18.0
* https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.19.0
Only the update to 1.20.0 will break the builds.
> fix(deps): bump Open Telemetry from 1.16.0 to 1.19.0

- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/producer/KafkaMessageProducer.java
The same behaviour is covered in the default method of the interface.
> refactor(server-kafka): remove unnecessary implementation

- sda-commons-dependencies/build.gradle
Release Notes:
* https://github.com/xerial/snappy-java/releases/tag/v1.1.9.0
* https://github.com/xerial/snappy-java/releases/tag/v1.1.9.1
* https://github.com/xerial/snappy-java/releases/tag/v1.1.10.0
* https://github.com/xerial/snappy-java/releases/tag/v1.1.10.1
It looks like [this PR](https://github.com/SDA-SE/sda-dropwizard-commons/pull/1098) has deactivated all minor updates.
> OK, I won't notify you about version 1.1.x again, unless you re-open this PR or update to a 1.1.x release yourself.
I hope that this PR will reactivate Dependabot's updates again.
>  fix(deps): bump org.xerial.snappy:snappy-java from 1.1.8.4 to 1.1.10.1

- sda-commons-server-weld/build.gradle
The probe bundle is responsible for most vulnerabilities in the weld bundle. However, it is not needed at runtime as it is a developer tool.
See
https://docs.jboss.org/weld/reference/3.1.9.Final/en-US/html/developmentmode.html
https://github.com/weld/core/pull/2792
weld-probe-core is also responsible for multiple breaking builds inside SIGNAL-IDUNA due to its multiple cves.
> Exclude weld-probe-core from weld-bundle

- sda-commons-dependencies/build.gradle
Release notes: https://github.com/junit-pioneer/junit-pioneer/releases/tag/v2.0.1
> fix(deps): bump org.junit-pioneer:junit-pioneer from 2.0.0 to 2.0.1

- sda-commons-dependencies/build.gradle
Bumped to the same version used in [Kafka 3.5.0](https://central.sonatype.com/artifact/org.apache.kafka/kafka_2.13/3.5.0)
> fix(deps): bump org.apache.zookeeper:zookeeper from 3.5.9 to 3.6.4

- sda-commons-shared-asyncapi/src/main/java/org/sdase/commons/shared/asyncapi/internal/JsonSchemaEmbedder.java
Is that the correct fix? Compare release notes:
* https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.14
* https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15
I felt this could be the location of the problem after reading https://github.com/FasterXML/jackson-core/issues/684
> fix(shared-async): Use matching property when replacing $ref

- .github/workflows/ignore-policy.rego
- sda-commons-dependencies/build.gradle
- sda-commons-server-jackson/src/test/java/org/sdase/commons/server/jackson/DateFormatObjectMapperTest.java
- sda-commons-shared-asyncapi/src/main/java/org/sdase/commons/shared/asyncapi/internal/JsonSchemaEmbedder.java
- sda-commons-shared-yaml/src/main/java/org/sdase/commons/shared/yaml/YamlUtil.java
> Another try to update snakeyaml

- sda-commons-server-openapi/src/main/java/org/sdase/commons/server/openapi/OpenApiBundle.java
This should make the output more reliable and fix random failing tests for OpenAPI comparison because the order of attributes changed.
> feat(server-openapi): sort output

- sda-commons-dependencies/build.gradle
- sda-commons-server-opentelemetry/src/main/java/org/sdase/commons/server/opentelemetry/OpenTelemetryBundle.java
* [1.29.0](https://github.com/open-telemetry/opentelemetry-java/releases/tag/v1.29.0)
* Fix gradle java version requirement warning (https://github.com/open-telemetry/opentelemetry-java/pull/5624)
* --> @SDA-SE/bedrock Does OpenTelemetry require Java 17?
* [1.28.0](https://github.com/open-telemetry/opentelemetry-java/releases/tag/v1.28.0)
* [opentelemetry-sdk-extension-autoconfigure](https://github.com/open-telemetry/opentelemetry-java/blob/v1.28.0/sdk-extensions/autoconfigure) is now stable! See "SDK Extension" notes below for changes made prior to stabilization.
* DEPRECATION: opentelemetry-exporter-jaeger and opentelemetry-exporter-jaeger-thrift are now deprecated with the last release planned for 1.34.0 (January 2024) (https://github.com/open-telemetry/opentelemetry-java/pull/5190)
> fix(deps): bump openTelemetryVersion from 1.27.0 to 1.29.0

- .github/workflows/mongodb.yml
Adding another step to the "mongodb" workflow because the workflow [fails](https://github.com/SDA-SE/sda-dropwizard-commons/actions/runs/6070029607/job/16465329950) (always? sometimes?) on master.
> chore: MongoDB workflow publishes unit test results

- build.gradle
alternative to #2724
More Info:
* [deprecation of reportOn](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/testing/TestReport.html#reportOn-java.lang.Object...-)
* [deprecation of buildDir](https://docs.gradle.org/current/userguide/upgrading_version_8.html#deprecated_project_builddir_can_cause_script_compilation_failure)
> chore: handle deprecations of `reportOn` and `buildDir`

- build.gradle
See [deprecation note](https://docs.gradle.org/current/javadoc/org/gradle/api/reporting/ConfigurableReport.html#setDestination-java.io.File-):
```
@Deprecated
void setDestination​(java.io.File file)
Deprecated.
Use [Report.getOutputLocation()](https://docs.gradle.org/current/javadoc/org/gradle/api/reporting/Report.html#getOutputLocation--).set() instead. This method will be removed in Gradle 9.0.
```
> chore: handle deprecations of `destination` and `buildDir`

- sda-commons-server-openapi/src/main/java/org/sdase/commons/optional/server/openapi/parameter/embed/EmbedParameterModifier.java
- sda-commons-server-openapi/src/test/java/org/sdase/commons/server/openapi/OpenApiBundleIT.java
- sda-commons-server-openapi/src/test/java/org/sdase/commons/server/openapi/apps/test/AnimalFilter.java
- sda-commons-server-openapi/src/test/java/org/sdase/commons/server/openapi/apps/test/HouseSearchResource.java
- sda-commons-server-openapi/src/test/java/org/sdase/commons/server/openapi/apps/test/OpenApiBundleTestApp.java
- sda-commons-server-openapi/src/test/resources/expected-openapi.yaml
Hi, the response model of search operations is currently restricted to exactly one list in the `EmbedParameterModifier` when using HAL links. But regarding the [REST guide](https://sda.dev/core-concepts/communication/restful-api-guide/#RESTfulAPIGuide-SHOULD%3AProvidecomplexqueriesusingsearchresources) normally a search operation contains a list with filters that is also a part of the response besides the result list. So the filter should also handle more than one list to get the correct `embed` query parameter documented in the OpenAPI
> fix(openapi): embed parameter modifier for search operations

- .github/workflows/ignore-policy.rego
- build.gradle
CVE-2023-4586 affects Netty which is used by Zookeeper.
As ZK is only used for Kafka testing this CVE does not affect production code and can be ignored.
> Feat/ignore CVE 2023 4586

- .github/dependabot.yml
* prevents PRs like this: https://github.com/SDA-SE/sda-dropwizard-commons/pull/2783
* stores our ignore rules as code instead of Dependabot magic when you use `@dependabot ignore ...`
> chore(dependabot): ignore jetty-bom 10-12

- .github/dependabot.yml
trying to get rid of #2789
Here's the documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#specifying-dependencies-and-versions-to-ignore
> chore(dependabot): ignore major and minor updates for Zookeeper

- sda-commons-dependencies/build.gradle
Jetty 9.4.52 was still picked up by consuming services.
> fix(deps): exclude Jetty from dropwizard-dependencies

- sda-commons-dependencies/build.gradle
This commit is a backport of https://github.com/SDA-SE/sda-dropwizard-commons/commit/1fc34ae6 for Release 2.x.x
> fix(deps-2.x.x): manage Jetty in dependencies

- sda-commons-client-jersey-wiremock-testing/src/main/java/org/sdase/commons/client/jersey/wiremock/testing/WireMockClassExtension.java
- sda-commons-client-jersey-wiremock-testing/src/main/java/org/sdase/commons/client/jersey/wiremock/testing/WireMockExtension.java
- sda-commons-client-jersey-wiremock-testing/src/test/java/org/sdase/commons/client/jersey/wiremock/testing/DeprecatedWireMockClassExtensionTest.java
- sda-commons-client-jersey-wiremock-testing/src/test/java/org/sdase/commons/client/jersey/wiremock/testing/DeprecatedWireMockExtensionTest.java
- sda-commons-client-jersey-wiremock-testing/src/test/java/org/sdase/commons/client/jersey/wiremock/testing/WireMockClassExtensionTest.java
In the meantime an official JUnit5 extension is provided by Wiremock. The extensions will be removed in the next major version of SDA Dropwizard Commons.
> feat(client-jersey-wiremock-testing): deprecate custom JUnit 5 Wiremock extensions and show migration in test changes

- .github/workflows/ignore-policy.rego
We might also get a new release of Dropwizard that will bump the Logback version: https://github.com/dropwizard/dropwizard/issues/7969
Anyway, this is a false positive.
> chore: ignore CVE-2023-6378

- .github/dependabot.yml
README states:
> Version 2.x.x only receives critical security updates until October 2023. We will only provide security updates for the libraries that are still compatible with Java 8.
>
> Please make sure to upgrade to version 5 as soon as possible.
Furthermore, the first beta of version 6 is approaching. Time to slowly fade out 2.x.x.
This will close several PRs and save a couple of resources.
> chore: disable Dependabot for release/2.x.x

- sda-commons-server-weld-example/build.gradle
- sda-commons-server-weld-example/src/main/java/org/sdase/commons/server/weld/WeldExampleApplication.java
- sda-commons-server-weld-example/src/test/java/org/sdase/commons/server/weld/WeldExampleApplicationITest.java
- sda-commons-server-weld-testing/src/main/java/org/sdase/commons/server/weld/testing/WeldAppExtension.java
- sda-commons-server-weld-testing/src/main/java/org/sdase/commons/server/weld/testing/WeldTestSupport.java
To reduce maintenance effort, we deprecated the [WeldAppExtension](https://github.com/SDA-SE/sda-dropwizard-commons/releases/tag/5.16.0) for removal. 
So far we did not show an alternative way for testing applications using Weld. This PR is meant to close this gap.
To have better coverage, the test of the example module is extended to verify a REST response ~~and then [migrated](https://github.com/SDA-SE/sda-dropwizard-commons/commit/77a38f37dcda0a3f5e28af650299f40259895440)~~. We decided to undo the deprecation and have test support for Weld in the future. The official extension requires too much overhead for a working integration test of a full Dropwizard application.
**Disclaimer**
We suggest to use pure Java with this library instead of an additional layer of magic like CDI. You may …
> CDI: Undo deprecation of `WeldAppExtension` and `WeldTestSupport`

- sda-commons-dependencies/build.gradle
Dependabot ignores spring-data-mongodb because https://github.com/SDA-SE/sda-dropwizard-commons/pull/2356 was closed. I have not succeeded to unignore it again.
"fixing" [CVE-2024-22233](https://www.cvedetails.com/cve/CVE-2024-22233/). We're not affected but update anyway to get rid of [security findings](https://github.com/SDA-SE/sda-dropwizard-commons/actions/workflows/cve-check.yml).
* [Release Notes](https://github.com/spring-projects/spring-data-mongodb/releases/tag/4.1.8)
> fix(deps): bump spring-data-mongodb from 4.1.7 to 4.1.8

- sda-commons-shared-certificates/src/test/java/org/sdase/commons/shared/certificates/ca/CaCertificatesBundleHttpsIT.java
It seems like Stackoverflow (sometimes?) blocks requests from GH runners.
> test(shared-certificates): use our own domain for testing

- sda-commons-dependencies/build.gradle
CVE-2024-1597 is already fixed by #3189
> fix(deps): bump transitive commons-compress to 1.26.0 to fix CVEs 2024-25710 and 2024-26308

- docs/server-trace.md
- sda-commons-server-trace/src/test/java/org/sdase/commons/server/trace/TraceTokenBundleTest.java
- sda-commons-server-trace/src/test/java/org/sdase/commons/server/trace/test/TraceTokenAwareExampleTask.java
- sda-commons-server-trace/src/test/java/org/sdase/commons/server/trace/test/TraceTokenTestApp.java
- sda-commons-server-trace/src/test/resources/test-config.yaml
Unfortunately, #359 can't be solved in the library. This PR documents how the desired Trace-Token functionality can be achieved for Dropwizard Tasks in each task itself.
> docs: show how trace-token can be used with tasks

- sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/consumer/strategies/autocommit/AutocommitMLS.java
Note: This fix only affects cases, when a subsequent message in the same poll causes the consumer to stop consuming. It may also cover scenarios when the application is shut down while the messages of this poll are handled.
> fix(kafka): treat continued handling errors like successful consumed message

- sda-commons-dependencies/build.gradle
BREAKING CHANGE:
Version 7 of `sda-dropwizard-commons` integrates MongoDB Java Driver 5.1.1. This upgrade introduces
some breaking changes, primarily due to the removal of deprecated methods. While many changes might
not directly impact your services, it's essential to review and test your application to ensure a
smooth transition.
For a comprehensive list of changes and detailed migration steps, please refer to
the [official MongoDB Java Driver 5.0 documentation](https://www.mongodb.com/community/forums/t/mongodb-java-driver-5-0-is-released/268913).
Updates `org.mongodb:mongodb-driver-core` from 4.11.2 to 5.1.1
Updates `org.mongodb:mongodb-driver-sync` from 4.11.2 to 5.1.1
Updates `org.mongodb:mongodb-driver-legacy` from 4.11.2 to 5.1.1
> fix(deps): bump mongoDbDriverVersion from 4.11.2 to 5.1.1

- .github/workflows/kafka-regression-test.yml
- Dockerfile
- sda-commons-dependencies/build.gradle
- sda-commons-server-kafka/src/test/java/DockerTest.java
The Bug has been introduced in DW Commons [7.0.49](https://github.com/SDA-SE/sda-dropwizard-commons/releases/tag/7.0.49). It is not covered in the lib but shows up in services that use Kafka and run in distroless images with a read only file system.
**Behavior**
The services crashes on startup when the Kafka producer is created with an exception:
```
java.lang.ExceptionInInitializerError: Cannot unpack libzstd-jni-1.5.6-3: Read-only file system
at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
at java.base/java.io.File.createTempFile(File.java:2170)
at com.github.luben.zstd.util.Native.load(Native.java:130)
at com.github.luben.zstd.util.Native.load(Native.java:86)
at com.github.luben.zstd.Zstd.<clinit>(Zstd.java:12)
at …
```
> Fix failure that occurs in distroless image with read only file system

- sda-commons-dependencies/build.gradle
As described in #3583, version 5.3.1.1 does not exist in [Maven Central](https://central.sonatype.com/artifact/org.apache.httpcomponents.client5/httpclient5-fluent/5.3.1/overview).
Fixes #3583
> fix(deps): change httpclient5-fluent to existing version 5.3.1

- sda-commons-client-jersey/src/main/java/org/sdase/commons/client/jersey/oidc/OidcClient.java
- sda-commons-client-jersey/src/main/java/org/sdase/commons/client/jersey/oidc/filter/OidcRequestFilter.java
- sda-commons-client-jersey/src/main/java/org/sdase/commons/client/jersey/oidc/rest/IssuerClient.java
- sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/oidc/OidcRequestFilterTest.java
We need to call "new OidcRequestFilter(jerseyClientBundle.getClientFactory(), oidcConfiguration, false);" multiple times in our service as there can be multiple Oidc. 
The code currently returns the following error: 
A metric named org.apache.hc.client5.http.io.HttpClientConnectionManager.oidc-client.available-connections already exists
java.lang.IllegalArgumentException: A metric named org.apache.hc.client5.http.io.HttpClientConnectionManager.oidc-client.available-connections already exists
We need a unique name for the oidc-client so that the error no longer occurs.
> fix: add uuid to IssuerClient oidc-client name for unique metric

- docs/server-key-mgmt.md
- sda-commons-server-key-mgmt/src/main/java/org/sdase/commons/keymgmt/KeyMgmtBundle.java
- sda-commons-server-key-mgmt/src/main/java/org/sdase/commons/keymgmt/manager/MapOrFailKeyMapper.java
- sda-commons-server-key-mgmt/src/main/java/org/sdase/commons/keymgmt/model/ValueMappingModel.java
- sda-commons-server-key-mgmt/src/test/java/org/sdase/commons/keymgmt/KeyMgmtBundleWithFailStrategyTest.java
- sda-commons-server-key-mgmt/src/test/java/org/sdase/commons/keymgmt/KeyMgmtBundleWithPlaceholderTest.java
This PR adds several fail strategies to the key management system that uses a predefined default value when specific key mappings are missing. The changes ought to be backward compatible.
> Enable the configuration of a default key mapping.

- sda-commons-dependencies/build.gradle
In tests with the latest commons version, wee errors:
> com.mongodb.MongoIncompatibleDriverException: Server at ****:27017 reports wire version 7, but this version of the driver requires at least 8 (MongoDB 4.2)
We may Drop support for AWS DocumentDB 4 later.
> Revert of mongodb driver update because of incompatibility with AWS DocumentDB 4
