SDA-SE/sda-dropwizard-commons

sda-commons-dependencies/build.gradle
This will enable polymorphic objects in serialization.
=> fix(deps): bump jackson-dataformat-hal from 1.0.5 to 1.0.7

sda-commons-dependencies/build.gradle
Matches version for okhttp needed by Jaeger
=> fix(deps): Push kotlin-stdlib to 1.3.50

.dependabot/config.yml
Reverts SDA-SE/sda-dropwizard-commons#141
Sad, this doesn't work 😢
=> Revert "chore: limit dependabot PRs for com.amazonaws:aws-java-sdk-bom"

README.md
=> docs: use official SonarCloud coverage badge in readme

sda-commons-dependencies/build.gradle, sda-commons-server-hibernate-example/build.gradle, sda-commons-server-hibernate-example/src/main/java/org/sdase/commons/server/hibernate/example/HibernateExampleApplication.java, sda-commons-server-hibernate/build.gradle, sda-commons-server-hibernate/src/test/java/org/sdase/commons/server/hibernate/test/HibernateApp.java, sda-commons-server-hibernate/src/test/java/org/sdase/commons/server/hibernate/test/HibernateNoPackageScanApp.java, sda-commons-server-hibernate/src/test/java/org/sdase/commons/server/hibernate/test/HibernatePackageScanApp.java, sda-commons-server-morphia-example/src/test/java/org/sdase/commons/server/morphia/example/MorphiaApplicationIT.java, sda-commons-server-morphia/build.gradle, sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleCustomConverterIT.java, sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleDefinedClassIT.java, sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleDisableLocalDateConvertersIT.java, sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleEnsureIndexesIT.java, sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleHealthCheckIT.java, sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleLocalDateConvertersIT.java, sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleNoEntityDefinedIT.java, sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleScanPackageByMarkerClassIT.java, sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleTracingIT.java, sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleValidationDisabledIT.java, sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleValidationIT.java, sda-commons-shared-asyncapi/src/test/java/org/sdase/commons/shared/asyncapi/internal/JsonSchemaEmbedderTest.java
This also brings an update of the Jetty libraries fixing CVE-2019-17638
=> fix(deps): Update Dropwizard to 1.3.25

sda-commons-server-morphia/src/test/java/org/sdase/commons/server/morphia/MorphiaBundleTracingIT.java
=> test(server-morphia): resolve warning about comparing incompatible types

sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/KafkaConfiguration.java, sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/config/HealthCheckConfig.java, sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/health/KafkaHealthCheck.java, sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/health/KafkaHealthCheckIT.java
Backports the changes of #570 to the 1.x.x branch.
=> feat(server-kafka): Make timeout for KafkaHealthCheck configurable

sda-commons-server-kafka/README.md
I added a configuration file example that can be copied and pasted to a new service.
What do you think about that? If this is a good idea, we should also add this to all the other bundles that require configurations.
=> docs(server-kafka): document a production-ready configuration for the kafka bundle

.dependabot/config.yml, .releaserc.yml, README.md, SECURITY.md
=> chore: remove 1.x.x related configuration and add a notice that 1.x.x is discontinued

sda-commons-starter-example/src/test/java/org/sdase/commons/starter/example/PlatformRequirementsIT.java, sda-commons-starter-example/src/test/java/org/sdase/commons/starter/example/SdaPlatformExampleApplicationIT.java
... to show how the basic setup of the new starter bundle works!
=> test(starter): add some integration tests

.github/workflows/java-ci.yml
Report junit results to PRs using [publish-unit-test-result-action](https://github.com/EnricoMi/publish-unit-test-result-action)
=> chore: add junit test report action

sda-commons-dependencies/build.gradle
TODOs:
Tested here:
- https://github.com/SDA-SE/malware-scanner-facade/pull/324
- https://github.com/SDA-SE/legally-compliant-document-delivery-service/pull/306
=> fix(deps): Update Kafka to 2.7.1

.github/workflows/java-ci.yml
=> chore: Update semantic release packages to latest major version

sda-commons-server-jackson/src/main/java/org/sdase/commons/server/jackson/ObjectMapperConfigurationUtil.java
Afterburner is not compatible with Java 17.
A warning was logged since Java 9.
There is intentionally no (conditional) change in the [`omShouldHaveSameModulesAsDefaultFromDropwizardButNoFuzzyEnumModule `](https://github.com/SDA-SE/sda-dropwizard-commons/blob/master/sda-commons-server-jackson/src/test/java/org/sdase/commons/server/jackson/TolerantObjectMapperTest.java#L33) so that we get notified when we introduce a Java 17 build and can decide what to do later.
=> fix: exclude Jackson Afterburner module in the latest JDKs

sda-commons-server-opentracing-example/src/test/java/org/sdase/commons/server/opentracing/example/OpenTracingApplicationIT.java
This should hopefully fix the failing action in the `master` branch.
=> test(server-opentracing-example): Add test for coverage

sda-commons-client-jersey-wiremock-testing/build.gradle, sda-commons-dependencies/build.gradle, sda-commons-server-openapi/build.gradle
=> fix(deps): exclude outdated version of Jackson

.github/workflows/fossa.yml
references:
- https://docs.github.com/en/actions/using-workflows/using-github-cli-in-workflows
- https://docs.github.com/en/rest/commits/statuses#create-a-commit-status
- https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_run
=> chore(fossa): add a step to try setting PR check

sda-commons-server-testing/src/test/java/org/sdase/commons/server/testing/EnvironmentRuleTest.java
More preparation for Java 16+.
=> test(server-testing): Disable tests that set env vars for Java16+

build.gradle
This PR is just re-using predefined Gradle functionality and getting rid of custom code. 😃 
Taken from: https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:complete_example
=> chore: Simplify publishing

sda-commons-client-jersey-example/src/test/java/org/sdase/commons/client/jersey/JerseyClientExampleIT.java, sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/ApiClientConfigurationTest.java, sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/ApiClientTest.java, sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/ApiClientTimeoutTest.java, sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/ApiClientWithoutConsumerTokenTest.java, sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/ClientConfiguredProxyTest.java, sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/ClientErrorUtilTest.java, sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/ClientProxyTest.java, sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/GenericClientTimeoutTest.java, sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/JerseyClientBundleTest.java, sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/SubtypeMappingAndValidationTest.java, sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/error/ClientRequestExceptionMapperTest.java, sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/error/ClientRequestExceptionTest.java, sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/filter/AddRequestHeaderFilterTest.java, sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/filter/ContainerRequestContextHolderTest.java, sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/oidc/OidcClientCacheDisabledTest.java, sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/oidc/OidcClientDisabledTest.java, sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/oidc/OidcClientTest.java, sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/oidc/OidcConfigurationTest.java, sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/proxy/annotation/SuppressConnectTimeoutErrorsToNullTest.java, sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/proxy/annotation/SuppressHttpErrorsToNullTest.java, sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/proxy/annotation/SuppressProcessingErrorsToNullTest.java, sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/proxy/annotation/SuppressReadTimeoutErrorsToNullTest.java, sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/test/ClientTraceTest.java
modules:
1.  sda-commons-client-jersey
2.  sda-commons-client-jersey-example
=> test(client-jersey): upgrading tests to JUnit 5

sda-commons-dependency-check/src/test/java/org/sdase/commons/dependency/check/DuplicateClassesTest.java, sda-commons-server-auth-testing/src/main/java/org/sdase/commons/server/auth/testing/AuthClassExtension.java, sda-commons-server-auth-testing/src/main/java/org/sdase/commons/server/auth/testing/AuthRule.java, sda-commons-server-auth/src/test/java/org/sdase/commons/server/auth/config/AuthConfigTest.java, sda-commons-server-auth/src/test/java/org/sdase/commons/server/auth/filter/JwtAuthFilterTest.java, sda-commons-server-auth/src/test/java/org/sdase/commons/server/auth/key/JwksKeySourceIT.java, sda-commons-server-auth/src/test/java/org/sdase/commons/server/auth/key/JwksKeySourceTest.java, sda-commons-server-auth/src/test/java/org/sdase/commons/server/auth/key/KeyLoaderSchedulerTest.java, sda-commons-server-auth/src/test/java/org/sdase/commons/server/auth/key/LoadedPublicKeyTest.java, sda-commons-server-auth/src/test/java/org/sdase/commons/server/auth/key/OpenIdProviderDiscoveryKeySourceIT.java, sda-commons-server-auth/src/test/java/org/sdase/commons/server/auth/key/OpenIdProviderDiscoveryKeySourceTest.java, sda-commons-server-auth/src/test/java/org/sdase/commons/server/auth/key/PublicKeyLoaderTest.java, sda-commons-server-auth/src/test/java/org/sdase/commons/server/opa/OpaBundleBodyInputExtensionTest.java, sda-commons-server-auth/src/test/java/org/sdase/commons/server/opa/OpaBundleClientConfigurationIT.java, sda-commons-server-auth/src/test/java/org/sdase/commons/server/opa/OpaBundleTest.java, sda-commons-server-auth/src/test/java/org/sdase/commons/server/opa/internal/OpaJwtPrincipalFactoryTest.java
modules:
1. sda-commons-dependency-check
2. sda-commons-server-auth
=> test(dependency-check,server-auth): upgrading tests to JUnit 5

sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/auth/testing/AuthBuilderTest.java, sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/auth/testing/AuthClassExtensionIT.java, sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/auth/testing/AuthClassExtensionProgrammaticIT.java, sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/auth/testing/AuthDisabledIT.java, sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/auth/testing/AuthDisabledJUnit5IT.java, sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/auth/testing/AuthRuleCustomizationIT.java, sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/auth/testing/AuthRuleCustomizationJUnit5IT.java, sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/auth/testing/AuthRuleIT.java, sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/auth/testing/AuthRuleProgrammaticIT.java, sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/auth/testing/CustomKeyLoaderConfigIT.java, sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/auth/testing/KeyLoaderProxyIT.java, sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/AuthAndOpaClassExtensionIT.java, sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/AuthAndOpaIT.java, sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/OpaClassExtensionIT.java, sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/OpaClassExtensionProgrammaticIT.java, sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/OpaConnectionMisconfiguredIT.java, sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/OpaDisabledIT.java, sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/OpaDisabledJUnit5IT.java, sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/OpaIT.java, sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/OpaJwtPrincipalInjectIT.java, sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/OpaProgrammaticIT.java, sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/OpaRequestsIT.java, sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/OpaResponsesIT.java, sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/OpaRuleIT.java, sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/OpaTimeoutIT.java, sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/PolicyExistsHealthCheckIT.java, sda-commons-server-auth-testing/src/test/java/org/sdase/commons/server/opa/testing/RequestExtraBuilderTest.java
module: sda-commons-server-auth-testing
=> test(server-auth-testing): upgrading tests to JUnit 5

sda-commons-server-auth-testing/src/main/java/org/sdase/commons/server/auth/testing/AuthRule.java, sda-commons-server-auth-testing/src/main/java/org/sdase/commons/server/opa/testing/OpaRule.java, sda-commons-server-mongo-testing/src/main/java/org/sdase/commons/server/mongo/testing/MongoDbRule.java, sda-commons-server-s3-testing/src/main/java/org/sdase/commons/server/s3/testing/S3MockRule.java, sda-commons-server-testing/src/main/java/org/sdase/commons/server/testing/RetryRule.java, sda-commons-server-testing/src/main/java/org/sdase/commons/server/testing/SystemPropertyRule.java
=> fix: Mark all provided JUnit 4 rules as deprecated

sda-commons-server-circuitbreaker/src/test/java/org/sdase/commons/server/circuitbreaker/CircuitBreakerBundleTestIT.java, sda-commons-server-circuitbreaker/src/test/java/org/sdase/commons/server/circuitbreaker/CircuitBreakerWrapperHelperTest.java, sda-commons-server-consumer/src/test/java/org/sdase/commons/server/consumer/ConsumerTokenBundleOptionalTokenTest.java, sda-commons-server-consumer/src/test/java/org/sdase/commons/server/consumer/ConsumerTokenBundleTest.java, sda-commons-server-cors/src/test/java/org/sdase/commons/server/cors/CorsTestIT.java, sda-commons-server-dropwizard/src/test/java/org/sdase/commons/server/dropwizard/bundles/DefaultLoggingConfigurationBundleWithConsoleAppenderTest.java, sda-commons-server-dropwizard/src/test/java/org/sdase/commons/server/dropwizard/bundles/DefaultLoggingConfigurationBundleWithEmptyConfigTest.java, sda-commons-server-dropwizard/src/test/java/org/sdase/commons/server/dropwizard/bundles/DefaultLoggingConfigurationBundleWithJsonLoggingEnabledTest.java, sda-commons-server-dropwizard/src/test/java/org/sdase/commons/server/dropwizard/bundles/DefaultLoggingConfigurationBundleWithUnconfiguredConsoleAppenderTest.java, sda-commons-server-dropwizard/src/test/java/org/sdase/commons/server/dropwizard/bundles/DefaultLoggingConfigurationBundleWithoutAppendersKeyTest.java, sda-commons-server-dropwizard/src/test/java/org/sdase/commons/server/dropwizard/bundles/DefaultLoggingConfigurationBundleWithoutConsoleAppenderTest.java, sda-commons-server-dropwizard/src/test/java/org/sdase/commons/server/dropwizard/bundles/DefaultLoggingConfigurationBundleWithoutLoggingKeyTest.java, sda-commons-server-dropwizard/src/test/java/org/sdase/commons/server/dropwizard/lifecycle/ManagedShutdownListenerTest.java, sda-commons-server-errorhandling-example/src/test/java/org/sdase/commons/server/errorhandling/ErrorHandlingExampleIT.java, sda-commons-server-healthcheck-example/src/test/java/org/sdase/commons/server/healthcheck/example/HealthExampleIT.java
1. sda-commons-server-circuit-breaker
2. sda-commons-server-consumer
3. sda-commons-server-cors
4. sda-commons-server-dropwiaard
5. sda-commons-server-errorhanding-example
6. sda-commons-server-healthcheck-example
=> upgrading tests to JUnit 5

build.gradle
https://github.com/google/google-java-format/releases/tag/v1.15.0
=> chore: Update googleJavaFormat to 1.15.0

sda-commons-server-spring-data-mongo/README.md, sda-commons-server-spring-data-mongo/src/test/java/org/sdase/commons/server/spring/data/mongo/inheritance/InheritanceMappingITest.java, sda-commons-server-spring-data-mongo/src/test/java/org/sdase/commons/server/spring/data/mongo/inheritance/model/AbstractPet.java, sda-commons-server-spring-data-mongo/src/test/java/org/sdase/commons/server/spring/data/mongo/inheritance/model/PrivateZoo.java
this is an alternative to #1973
=> Support inheritance in spring-data-mongodb by custom type alias

.github/dependabot.yml, .github/workflows/mongodb.yml, .releaserc.yml
based on the changes in https://github.com/SDA-SE/sda-dropwizard-commons/commit/1c454d525d1be00a9245ed9a3fd24915e0586ed6
=> chore: prepare security fix releases of v2

sda-commons-server-dropwizard/README.md, sda-commons-server-dropwizard/src/main/java/org/sdase/commons/server/dropwizard/bundles/LookupKeyAndOperators.java, sda-commons-server-dropwizard/src/main/java/org/sdase/commons/server/dropwizard/bundles/SystemPropertyAndEnvironmentLookup.java, sda-commons-server-dropwizard/src/main/java/org/sdase/commons/server/dropwizard/bundles/SystemPropertyAndEnvironmentSubstitutor.java, sda-commons-server-dropwizard/src/test/java/org/sdase/commons/server/dropwizard/bundles/LookupKeyAndOperatorsTest.java, sda-commons-server-dropwizard/src/test/java/org/sdase/commons/server/dropwizard/bundles/SystemPropertyAndEnvironmentLookupTest.java, sda-commons-server-dropwizard/src/test/java/org/sdase/commons/server/dropwizard/bundles/SystemPropertyAndEnvironmentSubstitutorTest.java
Example:
```yaml
welcomeMessage: ${WELCOME_MESSAGE | toJsonString:-"Hello,\nwelcome to wonderland!"}
username: ${USERNAME | toJsonString:-null}
password: ${PASSWORD | toJsonString:-null} 
```
Result without any properties defined:
```yaml
welcomeMessage: "Hello,\nwelcome to wonderland!"
username: null
password: null
```
Result with`WELCOME_MESSAGE=Yiehaa!`, `USERNAME=john`, `PASSWORD= s3cr3t"with\specials`:
```yaml
welcomeMessage: "Yiehaa!"
username: "john"
password: " s3cr3t\"with\\specials"
```
=> Ensure that Strings are rendered correctly in config.yaml

.github/workflows/sonar.yml
see https://sonarsource.atlassian.net/jira/software/c/projects/SONARGRADL/issues/SONARGRADL-93
=> chore(sonar): use new sonar task

sda-commons-dependencies/build.gradle
Release notes: https://github.com/dropwizard/dropwizard/releases/tag/v2.1.6
=> fix(deps): bump dropwizard from 2.1.5 to 2.1.6

sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/consumer/MessageListener.java, sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/consumer/strategies/MessageListenerStrategy.java, sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/consumer/MessageListenerErrorOnCloseTest.java, sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/consumer/strategies/MessageListenerStrategyOnCloseTest.java
=> Kafka Consumer: commit only what was handled on close

sda-commons-dependencies/build.gradle
* Tag: https://github.com/dropwizard/dropwizard/releases/tag/v2.1.7
* Changes: https://github.com/dropwizard/dropwizard/compare/v2.1.6...v2.1.7
=>  fix(deps): bump dropwizardVersion from 2.1.6 to 2.1.7

sda-commons-server-opentelemetry/src/test/java/org/sdase/commons/server/opentelemetry/AutoConfigurationTest.java
Assuming traces are logged asynchronously, this test may have failed if the trace is expected in the log immediately.
=> test(opentelemetry): wait for condition

sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/consumer/strategies/MessageListenerStrategyMetadataContextIntegrationTest.java, sda-commons-server-key-mgmt/src/test/java/org/sdase/commons/keymgmt/KeyMgmtBundleTest.java, sda-commons-server-spring-data-mongo/src/test/java/org/sdase/commons/server/spring/data/mongo/MongoConfigurationUtilTest.java
=> Reduce number of tests that cause reports about changed tests in PRs

sda-commons-client-jersey/src/test/java/org/sdase/commons/client/jersey/test/ClientTraceTest.java, sda-commons-dependencies/build.gradle, sda-commons-server-auth/src/test/java/org/sdase/commons/server/auth/key/OpenIdProviderDiscoveryKeySourceIT.java, sda-commons-server-opentelemetry/src/main/java/org/sdase/commons/server/opentelemetry/OpenTelemetryBundle.java
=> fix(deps): bump openTelemetryVersion from 1.19.0 to 1.27.0

sda-commons-server-prometheus/src/main/java/org/sdase/commons/server/prometheus/PrometheusBundle.java, sda-commons-server-prometheus/src/test/java/org/sdase/commons/server/prometheus/PrometheusBundleTest.java, sda-commons-server-prometheus/src/test/java/org/sdase/commons/server/prometheus/helper/MicrometerTestExtension.java
fixes metrics test issues 
see [https://github.com/SDA-SE/partner-ods/pull/747](https://github.com/SDA-SE/partner-ods/pull/747)
=> fix(prometheus): remove registry

sda-commons-server-weld/build.gradle
=> Fix 2.x.x weld probe core exclude

sda-commons-dependencies/build.gradle
- fix(deps): force bump commons-fileupload from 1.4 to 1.5
=> fix(deps): force bump commons-fileupload from 1.4 to 1.5

.github/workflows/cve-check.yml, .github/workflows/ignore-policy.rego
Also:
* publish message on success
* add ignore-policy.rego again
=> chore: use Slack bot for sending messages

.github/dependabot.yml
=> chore(dependabot): ignore major updates for jetty-bom

sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/consumer/strategies/synccommit/SyncCommitErrorHandler.java, sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/consumer/strategies/synccommit/SyncCommitMLS.java, sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/consumer/SyncCommitStrategyTest.java
=> feat: add option to register custom error handler for offset committing

sda-commons-server-spring-data-mongo/src/test/java/org/sdase/commons/server/spring/data/mongo/metrics/SpringDataMongoMetricsIT.java
The "cluster.id" tag contains some random digits and characters that often contain the age of the person "44"
=> test(server-spring-data-mongo): make test more reliable

sda-commons-server-openapi/build.gradle
fixing tests in sda-commons-server-openapi.
=> fix(server-openapi): make compatible with Jakarta

.github/dependabot.yml
Cleans up open pull requests that can't/should be merged ATM.
=> chore: add more ignores to Dependabot config

docs/server-open-api.md, sda-commons-server-openapi/src/main/java/org/sdase/commons/server/openapi/OpenApiBundle.java, sda-commons-server-openapi/src/test/java/org/sdase/commons/server/openapi/OpenApiGeneratorGenerateOpenApiTest.java, sda-commons-server-openapi/src/test/resources/expected-openapi.json
it can be used to generate the documentation without a running application
=> feat(server-openapi): provide public methods #generateOpenApiAsYaml/Json

sda-commons-server-prometheus/src/main/java/org/sdase/commons/server/prometheus/PrometheusBundle.java
Tested in partnerODS -> https://github.com/SDA-SE/partner-ods/pull/1024
=> fix(prometheus): clear registry after shutdown

docs/server-kafka.md, sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/config/ListenerConfig.java, sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/consumer/MessageListener.java, sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/consumer/strategies/MessageListenerStrategy.java, sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/consumer/strategies/autocommit/AutocommitMLS.java, sda-commons-server-kafka/src/main/java/org/sdase/commons/server/kafka/consumer/strategies/retryprocessingerror/RetryProcessingErrorMLS.java, sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/KafkaBundleWithConfigIT.java, sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/consumer/MessageListenerErrorIntervalTest.java, sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/consumer/RetryProcessingErrorStrategyIT.java, sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/consumer/RetryProcessingErrorStrategyTest.java, sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/consumer/strategies/MessageListenerStrategyMetadataContextIntegrationTest.java, sda-commons-server-kafka/src/test/java/org/sdase/commons/server/kafka/consumer/strategies/MessageListenerStrategyMetadataContextTest.java, sda-commons-server-kafka/src/test/resources/test-config-default.yml
Make the number of retries configurable in the ListenerConfig
=> feat(kafka): Make the number of retries configurable in the ListenerConfig
